markets/awesome-ruby

- README.md
Added CRM section.
[Fat Free CRM](https://github.com/fatfreecrm/fat_free_crm) project link added.
> Add 'CRM' section with 'Fat Free CRM' project link

- README.md
Add one more awesome project :boom:
> Github Changelog Generator

- README.md
lol_dba is a small package of rake tasks that scan your application models and displays a list of columns that probably should be indexed. Also, it can generate .sql migration scripts. http://plentz.github.com/lol_dba/
> Add lol_dba to database tools

- README.md
Dashboard that allows you to review all the open Pull Requests from your organizations and leave the classic "LGTM" comment. http://prs.crowdint.com/
> Add PR Dashboard to services and apps

- README.md
webgen is a static website generator that has been around since 2005. It is still actively maintained with the latest release a month ago.
> Add webgen

- README.md
@jasonlong Just for you to know :smile:
> Add geo_pattern

- README.md
A self-hosted, anti-social RSS reader.
> Add stringer

- README.md
See also http://cmusphinx.sourceforge.net/2014/10/pocketsphinx-ruby-is-available-on-github/
Not sure if the NLP category is the most appropriate.  Please advise if not and I'll change/add.
> Add pocketsphinx-ruby

- README.md
https://github.com/comfy/active_link_to
> Add active_link_to

- README.md
> Fix Ruby-LXC typo

- README.md
This repo has moved to https://github.com/commander-rb/commander
> update commander link

- README.md
I have updated the link to @kbrock's Trollop page. Please check if it's valid, thanks!
> Add Trollop with link to updated github page.

- README.md
This adds the weekly Ruby Rouges podcast to the resources section
> Add Ruby Rouges to Resources

- README.md
https://github.com/eval/envied
> add ENVied

- README.md
Hello there,
here is an actively maintained, well-tested, production-use package for Ruby.
Thanks for considering adding it :-)
-- Thibaut
> Add Kiba ETL

- README.md
Add knock gem in "Authentication and OAuth"
> Add knock gem to "Authentication and OAuth"

- README.md
Adding Vexor CI.
https://en.wikipedia.org/wiki/Vexor
https://vexor.io/
> Adding Vexor CI

- README.md
> Add Symmetric Encryption

- README.md
> Add RocketJob

- README.md
As mentioned here #472 
* http://www.railsbricks.net
```
I have left the Internet.
So Long, and Thanks for All the Fish
```
* https://rubygems.org/search?utf8=✓&query=railsbricks
```
NO GEMS FOUND
```
> Remove RailsBricks

- README.md
Adding SideCI.
https://www.sideci.com/
> adding SideCI to Services and Apps

- README.md
Should be up to par with the Quality Standards. Let me know if we're falling short!
> Added Finishing Moves

- README.md
Campo readme states project is inactive.
> Remove Campo

- README.md
Almost didn't even want to make a request for something so small, but it jumped out at me.
> tiny spelling fix; rouges to rogues

- README.md
> Add browse-everything to Cloud section

- README.md
> Add https://www.deppbot.com - Automated Security & Dependency Updates

- README.md
Seamless second database integration for Rails. SecondBase provides support for Rails to manage dual databases by extending ActiveRecord tasks that create, migrate, and test your application.
https://github.com/customink/secondbase
> Add SecondBase Gem

- README.md
The Lotus project has been renamed to Hanami.
> Replace Lotus with Hanami

- README.md
> Add prerender_rails

- README.md
Add scenic https://github.com/thoughtbot/scenic
> Add scenic gem

- README.md
Add scientist gem https://github.com/github/scientist
> Add scientist gem

- README.md
A CMS I've used on several project. I'm quite happy with it! Disclaimer: I'm not associated to the project or its developer(s) in any way.
Oh, and it respects the Quality Standards:
* Generally used and useful to the community.
* Actively maintained (even if that just means take care of open issues).
* Stable.
* Documented.
* Tests.
> Add Spina CMS

- README.md
> Added Rpush

- README.md
Docsplit - convert ppt and other documents into processable parts
> Add Docsplit

- README.md
> Replace ruby-band with weka

- README.md
https://github.com/choonkeat/attache
Preview: https://github.com/JuanitoFatas/awesome-ruby-1/blob/add-choonkeat-attache-to-file-uploading/README.md#file-upload
> Add choonkeat/attache to File Upload

- README.md
Hello,
I've added the [Awesome Jekyll](https://github.com/planetjekyll/awesome-jekyll) collection to the Static Site Generator section under the Jekyll entry. Would be great to see it added. If you have any questions, please let me know. Keep it up. Cheers.
> Add Awesome Jekyll

- README.md
> Add mutant

- README.md
> Add gemdiff

- README.md
https://github.com/chaps-io/access-granted
> Add AccessGranted

- README.md
[git_reflow](https://github.com/reenhanced/gitreflow) - An automated quality control workflow for Agile teams.
> Add git-reflow gem

- README.md
[Thredded](https://github.com/thredded/thredded) - Rails 4.2+ forum/messageboard engine. Its goal is to be as simple and feature rich as possible.
Website: https://thredded.org/
RubyGem: https://rubygems.org/gems/thredded
> Add Thredded

- README.md
Closes https://github.com/markets/awesome-ruby/issues/605
> add bulk_insert gem

- README.md
[Rodauth](https://github.com/jeremyevans/rodauth) is an authentication and account management framework for Rack applications. It's an alternative to Devise, Authlogic, Sorcery and others. Its advantages are:
* Full-featured, even has 2FA built-in
* Password hashes can't be accessed by the app database user (which means an attacker cannot access them even through SQL injection)
* Can be used with **any web framework** and **any ORM** (all other solutions are Rails-specific)
* All authentication logic can be encapsulated within a single Roda app
* Has support for JSON APIs, meaning all authentication & account management features are translated into the JSON API context (none of the other solutions have this ability)
* Extremely flexible
> Add Rodauth to Authentication

- README.md
The braintree gem has been around for many years and has over 2 million downloads.
Disclosure: I work at Braintree but that doesn't stop it from being awesome ruby 😉
> Add braintree gem

- README.md
Your go-to Ruby Toolbox. The Awesome Ruby collection + ordering by popularity, additional metadata and comparisons.
> Add 'Awesome Ruby @LibHunt' to the Resources section.

- README.md
I came across Shrine today while doing research on ruby file uploaders. I think it deserves to be listed.
> Added Shrine to file uploaders

- README.md
This adds [Bugsnag](https://bugsnag.com) to the list :)
> Add Bugsnag to Error Handling section

- README.md
> Add IdentityCache

- README.md
> Redis Store

- README.md
https://github.com/rossta/montrose, a simple library for expressing, serializing, and enumerating recurring events in Ruby
> Add montrose

- README.md
Fix and PR relate https://github.com/markets/awesome-ruby/issues/663
> fundamental

- README.md
This PR closes #679 as discussed in the issue.
I've added both resources in the alphabetical order to the list.
> Added links to NLP resources lists, closes #679.

- README.md
Add also its ActiveRecord integration plugin.
> Add state-machines to the state-machines list

- README.md
Hello I added the website http://rubyland.news under https://github.com/markets/awesome-ruby#resources. 
(https://github.com/markets/awesome-ruby/issues/704)
-Thank you 
(Closes #704)
> Added Ruby Land News

- README.md
More about knapsack
https://github.com/ArturT/knapsack
https://rubygems.org/gems/knapsack
> Add knapsack for optimal test suite parallelisation across CI nodes

- README.md
ActiveScaffold is an awesome gem for creating admin interfaces and quick prototyping etc.. - its's quite popular (ca. 920 GitHub-stars, 560.000 RubyGems-downloads) and has many contributors so it should be listed here!
ActiveScaffold
https://github.com/activescaffold/active_scaffold
https://rubygems.org/gems/active_scaffold
ActiveScaffold provides quick and powerful user interfaces for CRUD (create, read, update, delete) operations for Rails applications. It's excellent for generating admin interfaces, managing Data-Heavy Applications, creating Widgets or for quick prototyping. ActiveScaffold is completly customizable and offers a bunch of additional features including searching, pagination, layout control and overrides of fields, forms and templates.
> Add ActiveScaffold to Admin Interfaces

- README.md
I've used Petergate in several applications and I'm very pleased with it. It's much faster to integrate than some of the alternative authorization providers and is intuitive to use when declaring authorization rules.
- [Petergate Gem](https://rubygems.org/gems/petergate)
- [Documentation](https://github.com/elorest/petergate)
If you like the straight forward and effective nature of Strong Parameters and suspect that CanCan might be overkill for your project then you'll love Petergate's easy to use and read action and content based authorizations.
**It also has over 50,000 downloads and is actively maintained.**
- Efficient to implement.
- Authorization rules are declared in model and based on controller actions.
- Less overhead than some of the other authorization options.
---
Please help …
> Added petergate gem to the authorization list

- README.md
Waterfall https://github.com/apneadiving/waterfall 
A slice of functional programming to chain ruby services and blocks, thus providing a new approach to flow control.
There is no equivalent yet
---
> add waterfall

- README.md
Fix broken links and replace `RDoc` link with updated link.
> Fix broken links and replace with correct link

- README.md
AnyCable – http://anycable.io.
AnyCable allows you to use any WebSocket server (written in any language) as a replacement for your Ruby server (such as Action Cable).
AnyCable acts like a bridge between Ruby application and high-performant WebSocket server written in [Golang](https://github.com/anycable/anycable-go)/[Erlang](https://github.com/anycable/erlycable)/[whatever](https://github.com/anycable/anycable/wiki/Writing-Custom-AnyCable-Server) thus improving the performance and reducing system resources usage.
It's compatible with Action Cable protocol and can be easily plugged into existing Rails application.
It allows writing high-performant WebSocket in Ruby being backed by more powerful languages. Not sure there is something similar)
---
Please help us to maintain this collection …
> Add AnyCable

- README.md
Add new category: Captchas and anti-spam related tools.
Closes #662
---
> Add new category: Captchas and anti-spam solutions

- README.md
**Thanks for contributing to Awesome Ruby! Please take a look at the [contribution guidelines and quality standard](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md) first.**
factory_bot https://github.com/thoughtbot/factory_bot
A library for setting up Ruby objects as test data.
This is the same project as before (factory_girl) but the folks at Thoughbot have renamed it. [Naming History](https://github.com/thoughtbot/factory_bot/blob/master/NAME.md)
---
> update factory_girl as it is now named factory_bot

- README.md
> Updating ComfortableMexicanSofa description

- README.md
**Thanks for contributing to Awesome Ruby! Please take a look at the [contribution guidelines and quality standard](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md) first.**
Gibbon
An API wrapper for Mailchimp
It interacts with Mailchimp.
> Add Gibbon - Mailchimp API wrapper

- README.md
Hello,
if interested I've added a new category titled "Cryptocurrencies and Blockchains" - the idea is for bitcoin and friends. 
As a first gem in the category I've added the blockchain-lite gem / library - lets you build blockchains with crypto hashes from scatch (zero) - see [`openblockchains/blockchain.lite.rb`](https://github.com/openblockchains/blockchain.lite.rb) and incl. block types with proof-of-work and merkle tree hashes and more.
Cheers. PS: Thanks for the awesome page / list. Happy new year! Prosit 2018! Greetings from Vienna.
> New Category - Cryptocurrencies and Blockchains 

- README.md
> add awesome print

- README.md
Envyable on:
- GitHub: https://github.com/philnash/envyable
- Rubygems: https://rubygems.org/gems/envyable
- CodeClimate test coverage: https://codeclimate.com/github/philnash/envyable/coverage
> Adds Envyable to Configuration section

- README.md
Github Repo: 
https://github.com/pedrozath/coltrane
Rubygems: 
https://rubygems.org/gems/coltrane
Original blog post:
https://medium.com/@pedrozath/so-i-wrote-a-library-to-help-me-compose-music-ddb4ae7c8227
Post #1 on Reddit: https://www.reddit.com/r/ruby/comments/7tncey/any_ruby_musicians_and_enthusiasts_out_there/
Post #2 on Reddit: https://www.reddit.com/r/ruby/comments/84zk67/are_music_enthusiasts_still_there_some_coltrane/
Wiki page about how using the library: 
https://github.com/pedrozath/coltrane/wiki/Core-music-theory-library
It's a music theory library with a command-line interface. As a library, you can use it to make any kind of complex computation around Frequencies, Notes, Chords, Scales, Intervals and Progressions. 
As a command-line interface, you can quickly find notes, …
> Add Coltrane

- README.md
Trestle.io - https://github.com/TrestleAdmin/trestle && https://trestle.io/
A modern, responsive admin framework for Ruby on Rails.
Build a back-end in minutes that will grow with the needs of your application.
**Modern UI**
Trestle provides a modern, responsive interface that you can be proud to put in front of your users.
**Simple DSL**
Build your back-end quickly and easily using a powerful admin builder DSL. See the example below.
**Easy to Extend**
Take your admin even further using regular Rails templates, or create reusable form components.
**Customizable**
Make your Trestle admin your own by adding your company's colors, logo and more.
**Built with Bootstrap**
Bootstrap provides an extensive and familiar framework for customizing your Trestle admin.
**Plugin Ecosystem**
Core …
> Added 1 more admin Rails tool

- README.md
[Gemsmith](https://github.com/bkuhlmann/gemsmith) - A command line interface for smithing new Ruby gems.
- Builds a gem skeleton with enhanced Bundler functionality.
- Uses [Refinements](https://github.com/bkuhlmann/refinements) Ruby core library enhancements.
- Uses [Versionaire](https://github.com/bkuhlmann/versionaire) for semantic versioning.
- Uses [Runcom](https://github.com/bkuhlmann/runcom) for resource configuration management.
- Uses [Milestoner](https://github.com/bkuhlmann/milestoner) for consistent project/gem versioning.
- Uses [Pragmater](https://github.com/bkuhlmann/pragmater) for Ruby source pragma directives.
- Uses [Tocer](https://github.com/bkuhlmann/tocer) for README table of contents generation.
- Supports [Bundler Audit](https://github.com/rubysec/bundler-audit).
- …
> Added Gemsmith gem generator.

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/markets/awesome-ruby/722)
> Add Scout app (Performance monitoring) gem

- README.md
See https://github.com/markets/awesome-ruby/issues/855
> Add colorize in CLI Utilities

- README.md
> Add bcrypt-ruby to Encryption

- README.md
Blazer
https://github.com/ankane/blazer
Explore your data with SQL. Easily create charts and dashboards, and share them with your team.
It is using only SQL. All SQL can be stored and shared.
---
> add blazer

- README.md
https://smashing.github.io/
https://github.com/Smashing/smashing
Smashing is a successor (maintained fork) of Dashing.  A Sinatra based framework that lets you
build excellent dashboards
Maintained and updated version of Dashing - a dashboard framework already listed in awesome-ruby.
---
> add smashing and retirement of dashing

- README.md
Comes from https://github.com/markets/awesome-ruby/pull/884. 
Thanks!
> Update description for validates_zipcode

- README.md
The Ruby Bibliography
https://rubybib.org
It's a comprehensive list of research papers about Ruby.
Not aware of anything similar.
---
> Add RubyBib

- README.md
Sail
GitHub: https://github.com/vinistock/sail
RubyGems: https://rubygems.org/gems/sail
Featured in Ruby Weekly: https://rubyweekly.com/issues/422
Featured in dev.to: https://dev.to/iriskatastic/monthly-trending-ruby-on-rails-repositories-december-5-g7d
Featured in itnext: https://itnext.io/28-monthly-trending-ruby-on-rails-github-repositories-december-5-1a039707684
Featured in Syndicode: https://syndicode.com/2019/01/09/monthly-trending-ruby-on-rails-repositories-january-9/
Featured in afreshcup: https://afreshcup.com/home/2019/01/18/double-shot-2260
Sail a lightweight admin panel for managing configurations on a live Rails application. It allows you to configure the app without requiring a deploy by bringing a Setting model for the database.
It also comes with the capability to …
> Add Sail to configuration

- README.md
Komponent
https://github.com/komposable/komponent
An opinionated way of organizing front-end code in Ruby on Rails, based on components
We strongly emphasis to made a tool simple to use, following the Rails way, to organizing views based on components.  We provide generators to install, and generate new components with some options to use template engine and stylesheet engine of your choice. 
---
> Add Komponent

- README.md
InvoicePrinter, https://github.com/strzibny/invoice_printer
It's a simple Prawn-based library to make beautiful invoices in minutes. 
It's a competitive approach to generate such documents from HTML. And yes, this is faster, more efficient, easier, error prone and the resulting PDFs are smaller in size.
> Add InvoicePrinter

- README.md
[Decidim project page](https://decidim.org/)
[Decidim github](https://github.com/decidim/decidim/)
Decidim is a free open-source participatory democracy for cities and organizations generator build with ruby on rails.
Decidim is free and open-source.
Decidim helps citizens, organizations and public institutions self-organize democratically at every scale.
---
> Add Decidim

- README.md
Peatio
https://github.com/rubykube/peatio
Peatio is a free and open-source crypto currency exchange implementation with the Rails framework and other cutting-edge technology.
There is no known equivalent yet.
> Adding Peatio opensource project

- README.md
https://github.com/SciRuby/integration
This library is not bad. But the development has stopped and it seems that there are not many users. In my opinion, there are more awesome libraries in SciRuby. I propose a replacement.
---
> Removed integration

- README.md
Sqreen is a developer-friendly security tool for Ruby developers. It protects apps at runtime. 3-commands install. No configuration. No maintenance. 
More infos: 
https://rubygems.org/gems/sqreen
https://techcrunch.com/2016/09/13/sqreens-security-shield-automagically-blocks-attacks-on-your-web-app/
> Add Sqreen

- README.md
Blog posts: 
- https://semaphoreci.com/blog/2017/06/08/speeding-up-rails-pages-with-render-async.html
- https://medium.com/@nikolalsvk/rails-html-polling-without-javascript-dc28200d2a71
render_async renders partials to your views asynchronously. This is done through adding JavaScript code that does AJAX request to your controller which then renders your partial into a Rails view.
It supports many customization options, polling, caching, retry partial load after failure, error handling.
It uses simple JavaScript to fetch partials compared to [get_schiwfty](https://github.com/danielwestendorf/get_schwifty) which is based on ActionCable
---
> Add render_async to Optimizations category

- README.md
rbspy 
- https://github.com/rbspy/rbspy
- https://rbspy.github.io/
An easy-to-use sampling profiler for any Ruby process.
- There doesn't seem to be a project which is a dedicated plug-and-play sampling profiler yet.
- Written in Rust. Fast and reliable.
- Minimum setup required
---
> Add rbspy under Profiler and Optimization

- README.md
https://github.com/palkan/logidze
Logidze provides tools for logging DB records changes. Just like audited and paper_trail do (but faster).
https://evilmartians.com/chronicles/introducing-logidze
> Add Logidze

- README.md
[Sorbet](https://github.com/sorbet/sorbet)
A static type checker for Ruby.
Sorbet is the first major public release of a static type checker for Ruby. It could become a very useful developer tool to improve code quality and fix bugs. It's been developed by Stripe and is already in use by several major companies.
Resolves #929
---
> Add Sorbet

- README.md
prettier
* [github](https://github.com/prettier/plugin-ruby)
* [rubygems](https://rubygems.org/gems/prettier)
A automatic code formatter for Ruby.
Similar ones include rubyfmt, rufo, or some aspects of rubocop. The main difference is this uses prettier's main project so it gets the benefits of using their formatter.
> Add prettier

- README.md
Just updating the Rails version number that Refinery CMS supports :smile:
> Update Rails version target for Refinery CMS

- README.md
Zeitwerk
https://github.com/fxn/zeitwerk
An efficient and thread-safe code loader for Ruby.
No similar ones. This is new.
> Add Zeitwerk

- README.md
This pull request is not intended to add a projects, just intended to fix link.
> Follow Oga homepage change

- README.md
Add Database Consistency
[Database Consistency](https://github.com/djezzzl/database_consistency)
With database consistency, we make sure that our database constraints and the application constraints are kept in sync.
Enumerate comparisons.
> Add Database Consistency

- README.md
Github: https://github.com/Intrepidd/working_hours
RubyGems: https://rubygems.org/gems/working_hours
A modern ruby gem allowing to do time calculation with working hours.
---
> Add working_hours

- README.md
CSV Reader, see <https://github.com/csvreader/csvreader>.
CSV reader is a modern tabular data (line-by-line records) reader supporting "classic" CSV but also CSV Numerics, CSV <3 JSON, CSV <3 YAML, tab, space or fixed width fields (FWF) and many more flavors and dialects (incl. pre-configured database exports formats from PostgreSQL, MySQL and others, for example).
Two main differences: 1) Uses a "front-end" and "back-end" architecture for adding more parsers, that is, tabular data formats / flavors / dialects such as CSV Strict, CSV Numerics, CSV "The Right Way", and many more including fixed width fields, or space or tab separated (yes, TAB is it's own format). 2) Offers "classic" Csv.read / parse for returning records as array of string and new (!) CsvHash.read / parse for returing …
> Update Data Processing and ETL - Adding CSV Reader (Tabular Data in Many Formats / Flavors)

- README.md
Rename the project and update description.
---
> Update RQRcode gem name and description.

- README.md
Workarea
Project Page: https://www.workarea.com
Source Code: https://github.com/workarea-commerce
Documentation: https://developer.workarea.com
Workarea Blog: https://blog.workarea.com
RubyGems: https://rubygems.org/search?utf8=%E2%9C%93&query=workarea
Blog Posts About Workarea:
- https://www.sumoheavy.com/sumo-heavy-announces-partnership-with-workarea-commerce-platform/
- https://www.businesswire.com/news/home/20191110005014/en/Spell-Gypsy-Collective-Launches-Workarea-Commerce-Cloud
- https://todaysecommerce.com/2019/09/11/workarea-commerce-goes-open-source/
- https://www.cmo.com.au/article/668911/how-fashion-brand-has-cast-spell-over-customer-experience/
- https://www.prweb.com/releases/snuggle_bugz_selects_workarea_commerce_platform_to_power_richer_shopping_experiences_online_and_in_sto …
> Add Workarea to "eCommerce and Payments"

- README.md
I noticed that [git-up](https://github.com/aanand/git-up) is no longer maintained.
> Remove git-up

- README.md
Stemming libraries are used in pre-processing of data.
> Added stemming library

- README.md
Please allow me to shamelessly promote my project.
Awesome charts for your ruby app.
Github: https://github.com/styd/apexcharts.rb
Rubygems: https://rubygems.org/gems/apexcharts
Blog Post: https://hackernoon.com/32-most-popular-rails-repositories-on-github-in-july-2019-t5193yoh (No. 4 in the post)
It provides ruby/rails app with beautifully animated charts, not to mention their being interactive and responsive.
- Animate the charts more smoothly and in better motions.
- Support most popular types of charts, including Syncing Charts, Mixed/Combo Charts, and Brush Chart that you almost never find or at least can never create easily in any other chart library.
---
> Add ApexCharts.rb

- README.md
Closes https://github.com/markets/awesome-ruby/issues/988
**ARCHIVED BY OWNER / UNMANTAINED / MERGED**
* celluloid
* celluloid/reel
* stuff-classifier
* ratom
* legacy-linuxbrew
* dm-core
* abracadabra
* mailman
* doctor
* payola
* blender
* deploynator
* kochiku
* datamapper do
* authority
* facy
* rack-protection
* rails-footnotes
* time-lord
* rails-api
**UNMANTAINED / LAST COMMIT <= 2017**
* goliath 25 issues 3 open PR
* render_sync 26 issues 13 open PR
* websocket-rails 171 issues 33 open PR
* anemone 21 open PR
* volt 58 issues 18 open PR
* machinist 18 issues 15 open PR
* octopress 45 issues 5 open PR
* konacha 18 issues 4 open PR
* spork 101 issues 13 open PR
* yomu 19 issues 7 open PR
* searchlogic 115 issues 1 open PR
* rb-gsl 21 issues 7 open PR
* algorithms 11 issues 9 open PR …
> remove outdated repos

- README.md
StimulusReflex is a tool to help build reactive applications with the Rails tooling you already know and love.
- [Github](https://github.com/hopsoft/stimulus_reflex)
- [Docs](https://docs.stimulusreflex.com)
- [Demos](http://expo.stimulusreflex.com)
- [GoRails - Introduction to Stimulus Reflex](https://gorails.com/episodes/stimulus-reflex-basics)
- [Build a real-time Twitter clone in 10 mins with Rails and StimulusReflex](https://dev.to/codefund/build-a-real-time-twitter-clone-10-mins-with-rails-and-stimulusreflex-5h5c)
- [Remote Ruby - StimulusReflex with Nate Hopkins](https://remoteruby.transistor.fm/51)
StimulusReflex is a new way to craft modern, reactive web interfaces with Ruby on Rails. Building on the Stimulus JS framework and ActionCable, user interactions can be captured and …
> add stimulus_reflex gem

- README.md
Kimurai
https://github.com/vifreefly/kimuraframework
https://rubygems.org/gems/kimurai
Kimurai is a modern web scraping framework written in Ruby which works out of box with Headless Chromium/Firefox, PhantomJS, or simple HTTP requests and allows to scrape and interact with JavaScript rendered websites.
It supports many engines (headless chromium/firefox, phantomjs etc), highly configurable (headers, delay between requests etc), has built-in helpers (like save_to), has ability to run concurrent requests, handles request errors automatically and more.
Ps: the repo has been archived recently but the gem seems pretty stable.
---
> Add kimurai

- README.md
Rollbar 
* https://rubygems.org/gems/rollbar/versions/2.11.5
* https://github.com/rollbar/rollbar-gem
Rollbar helps development teams find and fix errors faster. Quickly pinpoint what’s broken and why. View exceptions from all of your languages, frameworks, platforms & environments in one place.
- powerful and Awesome service
- Easy setup.
- Simple and fast integration with many many tools and services .
- Multiple language support.
- Best rails exception handler.
---
> Adding rollbar gem

- README.md
- https://rubygems.org/gems/pubnub/versions/4.0.25
- https://github.com/pubnub/ruby
Describe features.
- Push Notification: Sending Mobile Alerts and Push Notifications.
- Message Actions: Performing actions on an existing message.
- chat.
- Presence Detection: Detecting Device presence online/offline states.
- Functions: Serverless, programmable functions to perform actions on the message.
- Easy to use.
- Simple Integrations.
- popular and high community usage
---
> Adding pubnub

- README.md
Consul is an authorization solution for Ruby on Rails .
- https://github.com/makandra/consul .
- https://rubygems.org/gems/consul
Consul is an authorization solution for Ruby on Rails where you describe sets of accessible things to control what a user can see or edit.
A typical use case in a Rails application is to restrict access to your ActiveRecord models. For example:
- Anonymous visitors may only see public posts
- Users may only see their own notes
- Only admins may edit users
Easy and very fun :heart: :smiling_face_with_three_hearts: 
---
> Add Consul Gem

- README.md
ActionMailer-like Notification System for your Ruby on Rails app.
* [GitHub Repo](https://github.com/excid3/noticed)
* [RubyGems](https://rubygems.org/gems/noticed)
* [GoRails Episode](https://www.youtube.com/watch?v=Scffi4otlFc)
Noticed is a gem for adding notifications to Rails apps. Notifications are really complicated to build and @excid3 has done the heavy lifting for us. The notifications are delivered in so-called delivery methods and noticed currently supports six different delivery methods out of the box.
Noticed is very Rails-like and abstracts the complex topic into an easy to use gem. 
If you are familiar with the ActionMailer framework you got the basic idea. 
---
> Add noticed gem

- README.md
Hey @markets 
just a typo: learninig -> learning
Cheers!
> learninig -> learning

- README.md
Hey @markets 
just a typo...
Cheers!
> Typo: bloging -> blogging

- README.md
[ActiveFlag](https://github.com/kenn/active_flag)
Bit array for ActiveRecord.
The most intuitive API compared to other solutions (listed in the README.md in the link above).
---
> Add ActiveFlag

- README.md
hitobito 人人 means "everyone"
github: https://github.com/hitobito/hitobito
web: http://www.hitobito.com
hitobito is an open source web application to manage organisation and communities with complex group hierarchies with members, events, courses, mailings, communication and a lot more.
hitobito is build by an awesome community with an architecture for a sustainable, long-term solution.
> Add hitobito

- README.md
RoRvsWild
https://github.com/BaseSecrete/rorvswild
RoRvsWild is a Ruby gem to monitor performances and quality in Rails applications.
This gem has a double mode: development, and production. 
It can be used without an account to profile your requests performances in your development environment.
It can also be used in your production and staging environments with an account on https://rorvswild.com. With such an account you also get extra benefits such as 30-day trace, background jobs monitoring, errors monitoring and notifications.
---
> Added RoRvsWild

- README.md
> add acts_as_archival to ActiveRecord Auditing section

- README.md
**Thanks for contributing to Awesome Ruby! Please take a look at the [contribution guidelines and quality standard](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md) first.**
[trick_bag](https://github.com/keithrbennett/trick_bag)
Assorted Ruby classes, modules, and methods to simplify and enhance your code.
Here is a summary of the features provided by `trick_bag`:
* `accessor` - returns lambda to simplify access to a deeply nested hash, as in 
`customer_accessor['contact_info.address.city']`
instead of `customer['contact_info']['address']['city']`
* `#access` - worker method for above, also publicly available for use; called as:
`access(customer, 'contact_info', 'address', 'city')` 
* `LinkedList` - a linked list implementation in Ruby
* `BufferedEnumerable` - …
> Add trick_bag to Misc section.

- README.md
**Runbook**
- https://github.com/braintree/runbook
- https://rubygems.org/gems/runbook
Runbook is a framework and Ruby DSL for system automation.
There are many system automation tools, but not many written in Ruby. Runbook is fully-featured and highly extensible.It can work within your application as a library or independently from the command line. It supports remote execution, Tmux integration, headless/automated mode, and more.
Resolves #940 
---
> Add Runbook

- README.md
MoneyTree - https://github.com/GemHQ/money-tree
A Ruby implementation of Bitcoin HD Wallets (Hierarchical Deterministic) BIP32.
It allows to generate keys for HD wallets. Have not seen alternatives yet.
---
> Added MoneyTree

- README.md
RedisWebManager - https://github.com/OpenGems/redis_web_manager
https://github.com/OpenGems/redis_web_manager
> Add RedisWebManager

- README.md
> add Runfile

- README.md
> add Neovim gem

- README.md
MotorAdmin: 
https://rubygems.org/gems/motor-admin
https://github.com/motor-admin/motor-admin-rails
A low-code Admin panel and Business intelligence Rails engine (no DSL - configurable from the UI).
Features:
* Customizable CRUD
* Custom actions
* Virtual attributes
* Forms builder
* SQL queries
* Data visualization
* Dashboards
* Email alerts
* Authorization
* Intelligence search
* I18n
* Optimized for mobile
* Configurations sync between environments
No-DSL or configuration files - everything can be configured via the settings directly from the UI. Also the project uses a modern front-end stack and doesn't require assets pipeline or webpacker as a dependency.
---
> Add motor-admin

- README.md
[Eventide Project](https://eventide-project.org)
- [GitHub](https://github.com/eventide-project)
- [RubyGems](https://rubygems.org/profiles/eventide)
- [Project Blog](https://blog.eventide-project.org)
A toolkit for writing autonomous event-sourced services in Ruby.
With a strong focus on software engineering fundamentals, along with event-sourcing and domain specific design principals, Eventide aims to help you write resilient, maintainable, idempotent, and autonomous (micro-)services.
---
> Add Eventide Project

- README.md
[TestBench](http://test-bench.software/)
[GitHub](https://github.com/test-bench/test-bench)
[RubyGems](https://rubygems.org/gems/test_bench)
[Project page](http://test-bench.software/)
TestBench is a test runner / framework that skips complexity and gives just enough structure for effectively developing tests without making using the testing framework more difficult than writing the code under test.
A lot of other testing frameworks require books to know how to use them fully, and it's questionable if that complexity provides commensurate value.  In contrast, a developer can read example TestBench files and have basically understood the entire library at a glance.  The assertions are kept simple (`assert` and `refute`), and the test files themselves can be run as just regular Ruby files. …
> Add TestBench

- README.md
See diff
See diff
Each one is the most famous in its type
> Security: add tools

- README.md
* https://github.com/darkleaf/date_range_formatter
* https://bestgems.org/gems/date_range_formatter
* https://github.com/markets/awesome-ruby/pull/323
The gem has reached [148K downloads](https://bestgems.org/gems/date_range_formatter) 🎉 
The simple tool to make work with date ranges in Ruby more enjoyable.
---
> Add date_range_formatter

- README.md
Sorcery supports current versions of Rails, not just 4 and 5.
> Update sorcery excerpt

- README.md
Add Taylor game engine
Taylor
Repo: https://github.com/HellRok/Taylor
Website: http://taylor.oequacki.com
Documentation: http://taylor.oequacki.com/documentation/taylor/
Taylor is a game engine built using mruby and raylib. Build in a very simple way for people to get into game development. This is trying to replicate the simplicity of QBasic but with a more of a modern approach.
Enumerate comparisons.
* Simplicity
* Speed
---
> Add Taylor

- README.md
* https://github.com/bia-technologies/lowkiq
* https://bestgems.org/gems/lowkiq
* https://www.reddit.com/r/ruby/comments/dlzz19/ann_lowkiq_ordered_background_jobs_processing/
In a few words, it is a background task server for special cases, excluding race conditions or deadlocks by design.
There is a comprehensive [Readme](https://github.com/bia-technologies/lowkiq).
It is widely used in companies: 
* https://bia-tech.ru/
* https://www.freshworks.com/
---
> Add Lowkiq

- README.md
- [Main repo](https://github.com/caxlsx/caxlsx)
- [RubyDoc](https://www.rubydoc.info/gems/caxlsx/)
- [Examples](https://github.com/caxlsx/caxlsx/tree/master/examples)
- [acts_as_caxlsx](https://github.com/caxlsx/acts_as_caxlsx) - Provides simple ActiveRecord integration
- [caxlsx_rails](https://github.com/caxlsx/caxlsx_rails) - Provides a `.axlsx` renderer to Rails, so you can move all your spreadsheet code from your controller into view files.
- Original [Blog Posts](http://axlsx.blog.randym.net/), and tutorials.
- Medium [tutorial](https://medium.com/@JasonCodes/ruby-on-rails-exporting-data-to-excel-b3b204281085).
- Author xlsx documents: Caxlsx is made to let you easily and quickly generate professional xlsx based reports that can be validated before serialization.
- Generate 3D Pie, …
> Update axlsx to caxlsx

- README.md
Name: Notion Ruby Client
URL: https://github.com/orbit-love/notion-ruby-client
A Ruby wrapper for the Notion API
It supports all Notion API endpoints (to this date), cursor-based pagination, and is based on a small set of up-to-date dependencies.
Closes #1101
---
> Add Notion Ruby Client

- README.md
[ruby-openai](https://github.com/ruby-openai)
Use the [OpenAI API](https://openai.com/blog/openai-api/) with Ruby! 🤖❤️
Generate text with ChatGPT, transcribe and translate audio with Whisper, or create images with DALL·E...
The most popular and widely used Ruby OpenAI library. Entirely community built and maintained and open source.
---
> Add ruby-openai

- README.md
As this is a popular gem for feature toggling / A/B testing.
Title and urls (GitHub, RubyGems, project page, blog posts, ...).
* Github: https://github.com/Unleash/unleash-client-ruby
* RubyToolbox: https://www.ruby-toolbox.com/projects/unleash
* RubyGems: https://rubygems.org/gems/unleash
* https://docs.getunleash.io/reference/sdks/ruby
This is the ruby client for Unleash, a powerful feature toggle system that gives you a great overview over all feature toggles across all your applications and services.
It is recommended (but not required) to be used in conjunction with the unleash-server.
This client will allow you to keep in sync features across multiple projects. And if you are running in a micro-services architecture, will also allow to to keep in sync even if some of the services …
> Add unleash gem

- README.md
**Title:** ActsAsRecursiveTree
[Github Link](https://github.com/1and1/acts_as_recursive_tree)
[RubyGems](https://rubygems.org/gems/acts_as_recursive_tree)
It makes ActiveRecord as a recursive tree where children can have children and so on. It provides a ton of methods to traverse the tree or load the whole tree at once and then traverse it.
It is almost like `acts_as_tree` but provides a ton of methods for loading the whole ancestory of a node and so on.
> Added ActsAsRecursiveTree

- README.md
Hot Glue
https://github.com/hot-glue-for-rails/hot-glue
Build plug-and-play scaffolding mixing generated ERB with the power of Hotwire and Turbo-Rails
Everything edits-in-place (unless you use --big-edit)
Automatically reads your models (make them, add relationships, and migrate your database before building your scaffolding!)
Excellent for CREATE-READ-UPDATE-DELETE (CRUD), lists with pagination
Great for prototyping, but you should learn Rails fundamentals first.
'Packaged' with Devise, Kaminari, Rspec, FontAwesome (optional)
Create system specs automatically along with the generated code.
Nest your routes model-by-model for built-in poor man's authentication.
Throw the scaffolding away when your app is ready to graduate to its next phase.
- This tool is a code generator tool. Other …
> Add Hot Glue

- README.md
The project is https://github.com/avo-hq/avo
Site: https://avohq.io/
Repo: https://github.com/avo-hq/avo
Rubygems: https://rubygems.org/gems/avo
---
> Add Avo to the CMS category

- README.md
https://github.com/fatkodima/pluck_in_batches
https://rubygems.org/gems/pluck_in_batches
A faster alternative to the custom use of `in_batches` with `pluck`.
> Add `pluck_in_batches`

- README.md
ActiveAnalytics
https://github.com/BaseSecrete/active_analytics
ActiveAnalytics is a Rails engine directly mountable in your Ruby on Rails application. It doesn't reveal anything about specific visitors. 
Compared to Ahoy
* Already includes a Rails Engine within a single gem that can be mounted via routes.rb in Rails.
* Allows sync writes to db, but also allows async writes to Redis if performance is an issue.
* Ahoy with AhoyCaptain is not compatible with sqlite3, this gem does not need it and is super simple.
> Add ActiveAnalytics to the Analytics section

- README.md
- Title: langchain.rb
- RubyGems: https://rubygems.org/gems/langchainrb
- GitHub: https://github.com/patterns-ai-core/langchainrb
---
> Creating "Artificial Intelligence" section and adding `langchainrb`

- README.md
https://github.com/healthie/activerecord_cursor_paginate
https://rubygems.org/gems/activerecord_cursor_paginate
Cursor-based pagination for ActiveRecord.
> Add `activerecord_cursor_paginate`

- README.md
* [Home](https://natalie-lang.org/)
* [GitHub](https://github.com/natalie-lang/natalie)
* [YouTube Hacking Sessions](https://www.youtube.com/playlist?list=PLWUx_XkUoGTq-nkbhnk6PN4m109ISo5BX)
* [Discord](https://discord.gg/hnHp2tdQyn)
Natalie is a work-in-progress Ruby implementation, compiled to C++, by [Tim Morgan](https://timmorgan.dev/) and contributors.
It includes an Ahead-of-time compiler and produces an executable.
---
> Added Natalie Ruby compiler.

- README.md
- Website: https://www.maglev.dev
- GitHub: https://github.com/maglevhq/maglev-core
- RubyGems: https://rubygems.org/gems/maglevcms
MaglevCMS is an open source page builder embeddable in any Rails 6+ application. It comes with a sleek UI, live editing and generators to create custom editable sections or blocks. 
A PRO version but not open source is also available for SaaS Rails applications which requires to support hundreds of landing pages or microsites.
This is probably the first page builder similar to Elementor available in Ruby on Rails. 
---
> add MaglevCMS

- README.md
https://github.com/thisismydesign/json-streamer
Stream JSON data based on various criteria (key, nesting level, etc).
---
> Add json-streamer
