- README.md
Added [RubyDNS](https://github.com/ioquatix/rubydns) project link under Misc section.
> Added RubyDNS project link under Misc

- README.md
In line with #341, I'd like to introduce another category called **Implementations/Compilers** where compilers like Opal and implementations like Rubinius & JRuby can be placed under.
What do you think about this @markets?
Thanks!
> Move Opal under Implementations/Compilers

- README.md
Neography - A thin Ruby wrapper to the Neo4j Rest API
> Add Neography to Database Drivers category

- README.md
[Neo4j.rb](http://neo4jrb.io) - A Neo4j OGM (Object-Graph-Mapper) for use in Ruby on Rails and Rack frameworks heavily inspired by ActiveRecord.
> Add Neo4j.rb to Database Drivers category

- README.md
A Ruby wrapper for the Slack API to Third Parties Services.
> Add A Ruby wrapper for the Slack API

- README.md
I actively use and maintain Surrounded to handle separating business logic from the objects that need it. It is well documented in the readme explanation and examples of use, description of implementation, and instruction on handling alternative behavior https://github.com/saturnflyer/surrounded/blob/master/README.md
> Add reference to Surrounded

- README.md
Derailed benchmark is some sort of collection of other gems to perform a benchmark. I wasn't sure if it should fit here as it's focused on Rails, but you can also use with Rack so I gave it a shot :smile: 
```
url: https://github.com/schneems/derailed_benchmarks
description: Go faster, off the Rails - Benchmarks for your whole Rails app
```
> Add Derailed Benchmark

- README.md
The gem's website: https://reidmorrison.github.io/semantic_logger/index.html
RubyGems: https://rubygems.org/gems/semantic_logger
From the website: "Next generation logging system for Ruby to support highly concurrent, high throughput, low latency systems
Semantic Logger takes logging in Ruby to the next level by adding several new capabilities to the commonly used Logging API."
> Add Semantic Logger

- README.md
Camaleon CMS is an alternative to [Wordpress](https://wordpress.org/) for Ruby on Rails. Thought it would be good to have it listed under `CMS` category.
> Add Camaleon CMS

- README.md
CombinePDF had been gaining traction and allows PDF manipulation without the need to install external libraries or helpers such as `iText` or `pdftk` - this allows CombinePDF also to work entirely in memory, parsing and outputting PDF data without using system calls or requiring temporary files.
Plezi is not as well known and is quite new to the playground, but it has an edge that makes it very powerful - it scales easily using Redis, allowing broadcasting and unicasting between Websockets to work seamlessly across different processes with no shared memory (i.e. having many Dynos on Heroku).
Plezi's Object Oriented model and Websocket API makes it reminiscent of the early days when writing for Rails was super simple. It makes writing Websocket applications that easy.
> add the `combine_pdf` and `plezi` gems

- README.md
Honeybadger is basically an error reporting mechanism similar to Airbrake. I have used both of these applications and both these applications' main objective is to capture and aggregate run time errors. In that aspect it is right to list Honeybadger under `Error handling` instead of the miscellaneous `Services and Apps` section.
Please check the website for proof: https://www.honeybadger.io/
> Honeybadger is an error handler at heart.

- README.md
Adding it in two categories because it can be used for both caching and object serialization (for APIs).
> Adding IFTTT/Kashmir

- README.md
Repos moved to a Github organization to facilitate shared ownership and maintenance
> Semantic Logger and Symmetric Encryption have moved

- README.md
A Ruby gem to convert Microsoft Word documents to Markdown.
**Supports**
1. Paragraphs
2. Numbered lists
3. Unnumbered lists
4. Nested lists
5. Italic
6. Bold
7. Explicit headings (e.g., selected as "Heading 1" or "Heading 2")
8. Implicit headings (e.g., text with a larger font size relative to paragraph text)
9. Images
10. Tables
11. Hyperlinks
> Word to Markdown link added

- README.md
> Redis Objects provides a Rubyish interface to Redis, by mapping Redis data types to Ruby objects, via a thin layer over the redis gem.
> Add Redis-objects gem

- README.md
[Hanna](https://github.com/rdoc/hanna-nouveau) is a better RDoc formatter with simplicity, beauty and ease of browsing in mind. Examples from Sequel's documentation:
* http://sequel.jeremyevans.net/rdoc/classes/Sequel/Dataset.html
* http://sequel.jeremyevans.net/rdoc/files/doc/active_record_rdoc.html
> Add Hanna to documentation

- README.md
Motivation: dry-rb is a growing in popularity collection of libraries. A significant part of these libraries are well suited for working with ORM and persistence tools. But I found it a bit more fair to put them in Abstraction part of list as you can find very nice dependency injection containers among dry-rb libraries.
Also I've decided to add all of the libraries with one link to dry-rb organization as I think it will be a consistent approach according to my reflections(that these are toolkit for increasing abstraction level).
> Add dry-rb

- README.md
See https://github.com/googleads/google-api-ads-ruby.
> Added google-api-ads-ruby gem to Third-party APIs

- README.md
Syro is a "Simple router for web applications." that handles basic routing similarly to [Sinatra](https://github.com/sinatra/sinatra). It's by the [same author](https://github.com/soveran) as [Cuba](https://github.com/soveran/cuba) and according to him:
> An initial idea was to release a new version of Cuba that broke backward compatibility, but in the end my friends suggested to release this as a separate library. In the future, some ideas of this library could be included in Cuba as well.
[Source](https://github.com/soveran/syro#trivia).
> Add Syro to Web Frameworks list

- README.md
`RuboCop` (capital C) is a formal name.
https://github.com/bbatsov/rubocop/blob/master/README.md
> Modify `Rubocop` to `RuboCop`

- README.md
Forem is [no longer maintained](https://github.com/rubysherpas/forem/blob/fb37858a51cfc8fe2ccd113e61af42546091fd27/README.md#no-longer-maintained).
Thredded now has a [homepage](https://thredded.org).
> Social networking: Remove Forem, update link to Thredded

- README.md
Some remarkable points:
- The only one jaro_winkler gem with C extension that can handle UTF-8 string so far.
- Part of [did_you_mean](https://github.com/yuki24/did_you_mean/blob/62a666ccbc21ded6b471ba883b935050b890f809/Gemfile), which has become built-gem since Ruby 2.3.
- Part of [roma](https://github.com/roma/roma/blob/a0311401d4e3fe17e218523c0e154084b55ca2e8/roma.gemspec#L48)
> Add jaro_winkler link

- README.md
We moved sorcery over to an org repo, and awesome ruby should reflect its new home.
> Update Sorcery to new org repo and added Rails 5

- README.md
Maintainers  suggest to use Administrate
> remove upmin-admin-ruby: framework is no longer actively maintained

- README.md
Thanks for the awesome list. I would like to add the slideshow (s9) gem that lets you generate presentations / talks / slideshows from your text sources (in markdown) with web templates. Cheers.
> add slideshow (s9) gem in presentations section

- README.md
[JSONAPI::Utils](https://github.com/tiagopog/jsonapi-utils) is probably one of easiest yet powerful ways for building [JSON API](http://jsonapi.org)-compliant APIs on Rails. It's all about defining a resource class and using the `jsonapi_render` on your controller actions.
> Add "JSONAPI::Utils" into "API Builder" section.

- README.md
Sadness, I know. They've decided not to continue the mini podcast.
> Ruby5 last episode was on September 20th, 2016

- README.md
Hello,
Thanks for this awesome ruby list. I'd like to add the feedparser gem (@ [github.com/feedparser/feedparser](https://github.com/feedparser/feedparser)) that just got updated to include the newest JSON Feed format (in addition to the "oldies" RSS and Atom). The library gets used by the pluto feed reader (among others) and runs, for example, the OpenStreetMap Blogs. Again thanks for the awesome ruby list. Keep it up. Cheers.
> Add feedparser - A feed parser and normalizer (Atom, RSS, JSON, etc) library.

- README.md
Thanks for maintaining this wonderful resource listing 👍🏻
I propose the addition of the iodine HTTP and Websocket server.
It's super fast and it's been here long enough for many of it's kinks to have been ironed out.
It's been tested with 20K active concurrent connections with good performance results and it supports native Websockets as well as HTTP.
It's optimized for (C)Ruby MRI, allowing many operations (network buffer management, IO bound tasks, timeout review, parsing etc') to run in true concurrency outside the GIL.
It maintains connection locks, preventing the same Websocket connection from having multiple `on_message` and `defer` events running at the same time.
I might be biased, but I think it's  as good as (if not better) than some of the web servers that were accepted to this …
> Add the iodine web server

- README.md
As proposed in ticket #719, the "Wrong" project is no longer maintained, and should be removed.
> Removed "Wrong" as it is no longer maintained (#719)

- README.md
Ruby Hyperloop is an active and vibrant project (similar to Volt) - please add to your fantastic list. This project was previously known as 'reactrb' but has been renamed Hyperloop.
Project website: http://ruby-hyperloop.io/
Github here: https://github.com/ruby-hyperloop
Thank you
> added Hyperloop to web frameworks

- README.md
The official repository is now under the MongoDB organization.
> Update Mongoid links

- README.md
Hi!
I created a new gem called [batch-loader](https://github.com/exaspark/batch-loader) which helps to avoid N+1 DB queries, HTTP requests, etc. In addition to the detailed description and some ASCII art in the [README](https://github.com/exaspark/batch-loader) I also created a small presentation. I'm using the [slides](https://speakerdeck.com/exaspark/batching-the-powerful-way-to-solve-n-plus-1-queries-every-rubyist-should-know) to describe to my internal team why the gem was created and how we can use it.
The gem can be used with any Ruby code, not only with GraphQL. In fact, we're using it with RESTful APIs on production. So, I was thinking about adding it to another category, the closest one could be `Data Processing and ETL`. But I decided to leave it in `GraphQL` for now, since it's …
> Add batch-loader

- README.md
[Git Cop](https://github.com/bkuhlmann/git-cop)
- Enforces a [Git Rebase Workflow](http://www.bitsnbites.eu/a-tidy-linear-git-history).
- Enforces a clean and consistent Git commit history.
- Provides Continuous Integration (CI) build server support.
- Provides Git Hook support for local use.
- Provides a customizable suite of style cops.
The only comparable gem in the current list is Overcommit. That said, Git Cop is purely focused on Git commits, hooks, and continous integration. It doesn't try deal with additional tooling like Overcommit does. If it helps, think of Git Cop to Git as Rubocop is to Ruby.
If you care about your project history (especially maintaining legacy code), this gem is highly recommended.
> Added Git Cop gem for keeping a clean Git history.

- README.md
TablePrint - [http://tableprintgem.com](http://tableprintgem.com)
TablePrint shows objects in nicely formatted columns for easy reading. It even lets you combine multiple DB tables into a single CLI view, contextualizing data across tables. It's incredibly flexible, yet simple, making it easy to see exactly the data you care about.
Perhaps you're wondering how table_print is different from some of your favorite IRB tools.
**terminal-table:**  An lower-level interface for turning arrays into tables.  TablePrint also displays tables, but the basic interaction is about your domain objects.  Much of the power of TablePrint is in the collection and combination of data, and the flexibility to see exactly the data you care about.  While terminal-table exposes an API for creating arbitrary tables …
> Add table_print gem to CLI Utilities

- README.md
**Thanks for contributing to Awesome Ruby! Please take a look at the [contribution guidelines and quality standard](https://github.com/markets/awesome-ruby/blob/master/CONTRIBUTING.md) first.**
[Docile](https://github.com/ms-ati/docile)
A tiny library that lets you map a DSL (domain specific language) to your Ruby objects in a snap.
I'm not aware of any other libraries that fill the same niche as Docile. It was written to extract the common patterns around usage of chained contexts for `instance_exec` or `instance_eval` from ad-hoc DSL code in various libraries. The goal is to have a common, community-maintained implementation of these patterns that avoids the common errors observed in the wild, such as local variables from the host object being unavailable to the code in the given block. …
> Add Docile

- README.md
[MicroMachine](https://github.com/soveran/micromachine)
A small, simple finite state machine implementation.
I think the README lays it out pretty simply:
> There are many finite state machine implementations for Ruby, and they all provide a nice DSL for declaring events, exceptions, callbacks, and all kinds of niceties in general.
>
> But if all you want is a finite state machine, look no further: this has less than 50 lines of code and provides everything a finite state machine must have, and nothing more.
> Add MicroMachine to "State Machines" section

- README.md
[connection_pool](https://github.com/mperham/connection_pool)
This project makes it easy to create connection pools for any database. ActiveRecord has it own Connection Pool, but you can use this project to create pooling for Redis, Dali or any Ruby network client.
- This is a very well tested, well estabilished and with lots of contribuitors
- It's simple to use
- It's maintained by [Mike Perham](https://github.com/mperham), the author and maintener of **Sidekiq**.
---
> Add connection_pool

- README.md
The "french" way of writing would be crêpe as it currently is. The name of the repo/gem is crepe though.
> Fix crepe name

- README.md
rib - http://rib.godfat.org/
A lightweight and extensible irb replacement.
This project has been in development for 6 years now, and is pretty mature. Many plugin's are provided to make your life easier.
Rib aims to be light compared to other alternatives, which means it starts very fast.
It also provide a simpler environment to develop its plugins.
It does not have lexical parsing bugs which IRB has (see the site for details).
---
> Add rib to IRB category

- README.md
https://github.com/jcupitt/ruby-vips
Ruby extension for the libvips image processing library. 
---
> Add ruby-vips

- README.md
[Pull Review](https://www.pullreview.com/) with website https://www.pullreview.com/, which redirects to [this blog post](http://blog.8thcolor.com/en/2018/02/the-end/)
From the blog post, it says pull review no longer has enough incoming to cover the costs, and ended about 3 weeks ago. I suppose the link could be left in memory/honour, but it doesn't seem to be active anymore.
Automated code review for Ruby and Rails - from style to security.
Other projects seem to still be worked upon.
---
> remove pull review

- README.md
Terrapin 
- [Github](https://github.com/thoughtbot/terrapin)
- [RubyGems](https://rubygems.org/gems/terrapin)
The project is the new version of the cocaine library, that is currently on the list.
All features are almost identical. 
Terrapin retains the same syntax/api as Cocaine. (examples from the README)
```
line = Terrapin::CommandLine.new("echo", "hello 'world'")
line.command # => "echo hello 'world'"
line.run # => "hello world\n"
```
and can have interpolated arguments like so
```
line = Terrapin::CommandLine.new("convert", ":in -scale :resolution :out")
line.command(in: "omg.jpg",
resolution: "32x32",
out: "omg_thumb.jpg")
```
---
> Add Terrapin (new version of the cocaine library)

- README.md
```
Post-install message from trollop:
!    The 'trollop' gem has been deprecated and has been replaced by 'optimist'.
!    See: https://rubygems.org/gems/optimist
!    And: https://github.com/ManageIQ/optimist
```
Resolve #832
> Replace `Trollop` (CLI) with `Optimist`

- README.md
Paperclip is now deprecated and should not be used so it seems like it should be removed.
ref: https://robots.thoughtbot.com/closing-the-trombone
https://github.com/thoughtbot/paperclip
---
> Remove paperclip as it has been officially deprecated

- README.md
This is just a fix of a typo for the description of "did_you_mean"
> fix typo in the description of "did_you_mean" & clean up trailing whitespace

- README.md
Adding Pagy gem to awesome ruby readme
[Pagy](https://github.com/ddnexus/pagy)
[Pagy Wiki](https://ddnexus.github.io/pagy/index)
Thanks for your work on *pagy* @ddnexux
Pagy is the ultimate pagination gem that outperforms the others in each and every benchmark and comparison.
Pagy is the ultimate pagination gem that outperforms the others in each and every benchmark and comparison. [Detailed Gem comparisons](https://ddnexus.github.io/pagination-comparison/gems.html)
---
> Adding Pagy gem to awesome ruby readme

- README.md
[Fast JSON API](https://github.com/Netflix/fast_jsonapi)
A lightning fast JSON:API serializer for Ruby Objects.
> Add Fast JSON API to API Section

- README.md
MidiSmtpServer
* [Homepage](https://github.com/4commerce-technologies-AG/midi-smtp-server)
* [RubyGems](https://rubygems.org/gems/midi-smtp-server)
MidiSmtpServer is a small and highly customizable ruby SMTP-Server. As a library it is mainly designed to be integrated into your projects as serving a SMTP-Server service.
* older one (MiniSmtpServer) is deprecated and less functional
* well tested and in production use for a number of years
* support for authentication
* support for encryption
---
> Add MidiSmtpServer, ruby SMTP-Server Component

- README.md
Mocha
It's very handy to stub and mock tests in Ruby.
Allows to stubs methods
Fits very well with Minitest an other frameworks
Allows full ot partial mocking
> Adding mocha framework from mocking and stubbing in Ruby

- README.md
https://opensuse.github.io/gitarro/
gitarro run tests on GitHub PRs using almost any script,language or binary, it integrate easy with other tools.
Gitarro use the official Github API, written in Ruby (Octokit)
There is no such a project for ruby at moment.
___
> Add gitarro rubygem

- README.md
Unfortunately, this service is no longer running and can be removed
from the list of choices. The feed was ended on
[2017-06-04](http://greenruby.org).
> Removed Green Ruby News from resources section.

- README.md
https://github.com/crohr/syslogger
A drop-in replacement for the standard Logger Ruby library, that logs to the syslog instead of a log file.
* it logs to the syslog instead of a log file
* Contrary to the SyslogLogger library, you can specify the facility and the syslog options.
See issue https://github.com/markets/awesome-ruby/issues/844
---
> Add syslogger in Logging

- README.md
[Dependabot](https://dependabot.com)
Creates dependency update pull requests for Ruby projects (and JS, Python and PHP).
Different to `deppbot` (which is already listed) as it creates individual PRs for each update, rather than one bulk update, and also suggests out-of-range updates when available. Used by over 600 Ruby projects and listed in the GitHub marketplace. Also, it's free for private repos on personal accounts.
---
> Add Dependabot - Automated dependency update pull requests

- README.md
In Hanami project, we built Hanami CLI as a general command line interface framework for ruby, it is used in Hanami framework but it can be used alone.
https://github.com/hanami/cli
https://rubygems.org/gems/hanami-cli
http://hanamirb.org
You can build command line interfaces using Ruby
---
> Add hanami cli as CLI builder

- README.md
* https://github.com/ruby-numo/numo-narray
* https://rubygems.org/gems/numo-narray
N-dimensional array
This project is the successor to Ruby/NArray.
Compared to NMatrix
* NArray is faster. Almost as fast as Numpy right now.
https://www.slideshare.net/naitoh1/rubydata-tokyo-meetup-2018-naitoh-123262737
* Easy to install. 
* Long history. 
* A blank from the old version.
* But development is active in 2019. (NMatrix is not active) 
* It has GPU version. 
https://github.com/sonots/cumo
* It has a powerful machine learning library
https://github.com/yoshoku/SVMKit
* It has a deep learning Library
https://github.com/red-data-tools/red-chainer
* It is Not Sciruby project. 
* Some popular Sciruby gems use nmatrix.
* So fewer stars, fewer contributors
* It has no coarse matrix implementation
> replace NArray with Numo::NArray

- README.md
Standby is a simple, easy to use gem for ActiveRecord that enables conservative reading from standby databases, which means it won't automatically redirect all SELECTs to standbys.
> Add Standby

- README.md
Website: [https://honeyryderchuck.gitlab.io/httpx/](https://honeyryderchuck.gitlab.io/httpx/)
Repo: [https://gitlab.com/honeyryderchuck/httpx](https://gitlab.com/honeyryderchuck/httpx)
HTTPX is an HTTP client library for the Ruby programming language.
Among its features, it supports:
- HTTP/2 and HTTP/1.x protocol versions
- Concurrent requests by default
- Simple and chainable API (based on HTTP.rb, itself based on Python Requests)
- Proxy Support (HTTP(S), Socks4/4a/5)
- Simple Timeout System
- Lightweight (explicit feature loading)
And among others
- Compression (gzip, deflate, brotli)
- Authentication (Basic Auth, Digest Auth)
- Cookies
- HTTP/2 Server Push
- H2C Upgrade
- Redirect following
In Ruby, HTTP client implementations are a known cheap commodity. Why this one? …
> Add HTTPX gem - a cool http client

- README.md
Added Serverless list
Added FaaStRuby to the Serverless list
* https://github.com/FaaStRuby/
* https://rubygems.org/gems/faastruby
* https://faastruby.io
* https://dev.to/jgaskins/faastruby-serverless-functions-as-a-service-for-ruby-and-crystal-2849
* https://onebitcode.com/faastruby-serverless-ruby/
FaaStRuby is a serverless FaaS platform for Ruby developers.
* It has no cold starts, so you can actually develop a web application with it.
* Easy to use CLI.
* Don't need to learn a framework.
---
> Added FaaStRuby

- README.md
https://github.com/mrkn/pycall.rb
Access all Python functions from Ruby.
https://github.com/mrkn/pycall.rb/blob/master/examples/notebooks/classifier_comparison.ipynb
PyCall is useful when you use pandas, numpy, scikit-learn, keras functions inside Ruby application.
There is no similar project in Ruby.
There is PyCall.jl in Julia Lang. 
---
> add PyCall to Scientific

- README.md
> Rename "Artificial intelligence" to "Machine learning"

- README.md
This is a SciRuby project. 
A toolkit for publishing scientific results to the semantic web. 
The last update is in 2013.
We should exchange this for more important gems. For example [rubex](https://github.com/SciRuby/rubex).
---
> Removed "PubliSci"

- README.md
This is a SciRuby project. (Vega/D3-based plotting gem for Ruby.)
The last update was in 2014. Maintenance is actually stopped.
SciRuby develops Nyaplot, GnuplotRB, Daru::View, rubyplot after this.
We should exchange plotrb for another gem. For example [Daru::View](https://github.com/SciRuby/daru-view)
---
> Removed "plotrb"

- README.md
Sniffer – [http://github.com/aderyabin/sniffer](http://github.com/aderyabin/sniffer)
Hooks into Net::HTTP, Patron, Curb, Typhoeus and other Ruby HTTP libraries to log outgoing requests for further analysis.
It allows analyze outgoing HTTP requests and responses.
---
> Add Sniffer

- README.md
https://github.com/jhawthorn/discard - Soft deletes for ActiveRecord done right.
A simple ActiveRecord mixin to add conventions for flagging records as discarded.
It's the recommended gem by the Paranoia core.
> `paranoia` has some surprising behaviour (like overriding ActiveRecord's `delete` and `destroy`) and is not recommended for new projects. See [`discard`'s README](https://github.com/jhawthorn/discard#why-not-paranoia-or-acts_as_paranoid) for more details.
---
> Add discard gem

- README.md
https://github.com/yoshoku/rumale
This library provides a wide range of machine learning algorithms with a uniform interface like scikit-learn. The author is developing in contact with red-data-tools and sciruby-jp. This project has the potential to become Ruby's standard machine learning library in the future. Recently SVMKit was renamed to Rumale (RUby MAchine LEarning) .
Compared to [ai4r](https://github.com/SergioFierens/ai4r), Rumale
- is faster ( using NArray )
- is reliable ( Developed by a data scientist )
- has a consistent interface ( like scikit-learn )
- code is easy to read. 
---
> Add Rumale

- README.md
https://github.com/marloncarvalho/ruby-datumbox
This library has not been updated for 5 years and development has stopped. I suggest replacing it with Rumale.
> Removed Datumbox

- README.md
https://github.com/SciRuby/daru-view
This Library is for data visualization. Daru-view visualizes Daru::Dataframe and Daru::Vector using Google Charts or Highcharts. It is usually used on Jupyter Notebook.
There is no user-friendly visualization tool in Ruby. I know that Daru::View is far from perfect. But, in some ways, Daru::View is the best visualization library in Ruby right now.
Compared to numo-gnuplot, gnuplot, gnuplotrb, nyaplot, daru-plotlly, rbplotly, daru-plotly, rubyplot, charty,
Daru::View
- is an extension of Daru, which is the most used data frame in Ruby.
- visualize not only series but also data frames. 
- is active. ( There are a lot of similar projects that have finished development. )
- works offline. 
- is interactive.
- can be used with Jupyter Notebook.
- has good …
> Add Daru::View

- README.md
[webpush](https://github.com/zaru/webpush)
[webpush | Rubygems](https://rubygems.org/gems/webpush/)
This gem makes it possible to send push messages to web browsers from Ruby backends using the Web Push Protocol. It supports Message Encryption for Web Push to send messages securely from server to user agent.
I have not seen other implementations as far as I know.
---
> Add webpush

- README.md
**Health Monitor Rails**
Github: https://github.com/lbeder/health-monitor-rails
RubyGems: https://rubygems.org/gems/health-monitor-rails
A mountable Rails plugin to check health of services(DB, sidekiq, Redis) used by the app.
- Simple and minimalistic
- Easy to add new services according to our need
- Offers different response formats(HTML/JSON/XML) for "/check"  endpoint
---
> Add health monitor gem

- README.md
`timezone` - https://github.com/panthomakos/timezone
This gem provides current and historical timezones - with accurate transformations between local and UTC times. All data is based off the most recent [IANA Timezone Database](https://www.iana.org/time-zones). The gem also includes a Ruby API for looking up timezones (based on latitude - longitude coordinates) from Geonames or Google.
* Up-to-date and in-memory data from IANA Timezone Database - which is not dependent on system `tzdata` packages being installed.
* Easy lookups from Geonames and Google.
* Best-guess handling of time conversions that fall during daylight savings time transitions.
---
> Add timezone to Date and Time Processing

- README.md
`pry-rails`
https://github.com/rweng/pry-rails
Avoid repeating yourself, use pry-rails instead of copying the initializer to every rails project. This is a small gem which causes rails console to open pry. It therefore depends on pry.
Useful and bring pry to rails console
> Add pry-rails to debugging tools

- README.md
Title: `tabulo`
GitHub: https://github.com/matt-harvey/tabulo
RubyGems: https://rubygems.org/gems/tabulo
Tabulo is an ASCII table generator with a DRY, "column-based" API. Its features make it especially well-suited to tabulating large, unwieldy data sets.
* The initialization interface is structured around building up the table column-by-column, rather than row-by-row. This makes for DRYer initialization code, since the ordering of the columns is expressed only once, rather than being duplicated within each row (and, in particular, between the header row and the body rows).
* You can "shrinkwrap" the table so that it automatically sizes each column, but stops at a certain overall maximum width (which you usually want to be the width of your terminal). This is especially useful when …
> Add Tabulo to CLI Utilities list

- README.md
[Cloudsmith](https://cloudsmith.io) - https://cloudsmith.io
This PR adds a link to [Cloudsmith](https://cloudsmith.io), which is a package management service SaaS. It's commercial, but it is completely free for open-source and it has generous free tiers otherwise. It has first-class support for Rubygems-compatible repositories (and many other package formats, such as Python/Npm), plus org/teams management, granular access controls, private repositories, repository-specific entitlements, a worldwide content distribution network, webhooks, access logs, etc.
It's similar to [Gemfury](https://gemfury.com), which is another excellent service for managed hosting of Rubygems. Cloudsmith has a focus on simplicity and an ethos for being as secure as possible by default, which is seen in the …
> Add Cloudsmith (a Rubygems-compatible service)

- README.md
GitHub: https://github.com/square/connect-ruby-sdk
RubyGems: https://rubygems.org/gems/square_connect
Project Page: https://docs.connect.squareup.com/sdks
The Square Connect SDK provides an interface a number of Square APIs for taking payments and running a business.
Square is a payment platform that has processed billions of transactions. This gem provides access to APIs for Employees, Labor, Inventory, Orders, and other APIs needed to run a business.
---
> Add Square Connect Ruby SDK

- README.md
humidifier
* [github](https://github.com/kddeisz/humidifier)
* [rubygems](https://rubygems.org/gems/humidifier)
A ruby CLI/library for interacting with the AWS CloudFormation API.
There are a couple of other CloudFormation ruby libraries (like SparkleFormation). In general most of these libraries act as a fancy JSON generator. This library instead gives you domain objects to represent AWS resources.
> Add humidifier

- README.md
[Agoo](https://github.com/ohler55/agoo)
[On RubyGems](https://rubygems.org/gems/agoo)
[Benchmarks](https://github.com/planetruby/awesome-webservers/blob/master/benchmark/benchmarks.md)
[More benchmarks](https://github.com/the-benchmarker/web-frameworks)
Agoo is fast! It also support WebSockets, SSE, and GraphQL.
- Faster than any other Ruby web server according to independent benchmarks listed above.
- Supports a simple to use GraphQL API.
- Supports WebSockets and SSE using the proposed Rack WebSocket API
> Add Agoo web server

- README.md
Rein - Database constraints made easy for ActiveRecord.
- Github: https://github.com/nullobject/rein
- Rubygems: https://rubygems.org/gems/rein
Data integrity is a good thing. Constraining the values allowed by your application at the database-level, rather than at the application-level, is a more robust way of ensuring your data stays sane.
Unfortunately, ActiveRecord doesn't encourage (or even allow) you to use database integrity without resorting to hand-crafted SQL. Rein adds a handful of methods to your ActiveRecord migrations so that you can easily tame the data in your database.
There are no other gem related to database constrains on the list.
> Add Rein gem to Database Tools section

- README.md
Since this isn't an addition, I don't know how to follow the pull request template on this one.
I was looking through and saw that Gitrob — albeit being an interesting idea for a package — is not a Ruby tool.
Since this is awesome Ruby, I thought we should also curate as much as we collect
> Remove Go Package: Gitrob

- README.md
Changes link from broken http://manageiq.org/optimist/ to https://github.com/ManageIQ/optimist
> Adjusts broken optimist link to Github URL

- README.md
Rubocop Rails: [Github](https://github.com/rubocop-hq/rubocop-rails) - [RubyGems](https://rubygems.org/gems/rubocop-rails)
Rubocop Performance: [Github](https://github.com/rubocop-hq/rubocop-performance) - [RubyGems](https://rubygems.org/gems/rubocop-performance)
Rubocop Rspec: [Github](https://github.com/rubocop-hq/rubocop-rspec) - [RubyGems](https://rubygems.org/gems/rubocop-rspec)
Since the release of Rubocop version 2 some previously integrated supports was moved into other gems (named extensions).
This is a list of basic rubocop extension for (mainly) RoR development. 
is there anyone else doing the same job? 😎 
---
> Added rubocop extensions

- README.md
Closes #954, which has a :+1: from @markets, which I'm assuming means this gem meets at least preliminary criteria for inclusion.
Sentimental
[GitHub repo](https://github.com/7compass/sentimental)
[Rubygems page](https://rubygems.org/gems/sentimental)
A library for sentiment analysis and n-gram parsing.
Simple interface and intuitive interface.
---
> Add Sentimental gem to NLP section

- README.md
> Add Timber.io to the list of logging libraries

- README.md
add buffer API to Third Party
Buffer (https://github.com/bufferapp/buffer-ruby)
https://buffer.com/developers/libraries/ruby
It is a library for connecting with the Buffer Application specifically for tuby 
Only ruby library for buffer by buffer app
---
> add Buffer -  a Ruby Wrapper for the Buffer API

- README.md
https://github.com/tmm1/stackprof
https://rubygems.org/gems/stackprof/
https://github.com/palkan/test-prof
https://test-prof.evilmartians.io/
https://rubygems.org/gems/test-prof
`stackprof` is a profiling gem, like `ruby-prof`, but it allows you to generate html [flame graphs](https://camo.githubusercontent.com/cd1f56caa017a2ff71ca3f6450c3ac8e03eb1272/687474703a2f2f692e696d6775722e636f6d2f45776e647267442e706e67), which I think is way cool. 
`test-prof` is a set of tools that integrates with `ruby-prof` and `stackprof` and makes life easier to analyse profiling output info.
Quite surprised these two weren't included for profiling stack as are very well known gems (or that was my assumption). First one is [supervised by tenderlove](https://github.com/tmm1/stackprof/commits?author=tenderlove) …
> Add stackprof and test-prof gems for "Profiler and Optimization"

- README.md
cane has not had a commit for four years; and the [README](https://github.com/square/cane) recommends using Rubocop instead of cane for new projects.
> Remove cane

- README.md
`git_curate`: A tool to take control of your local git branch proliferation.
* Repo: https://github.com/matt-harvey/git_curate
* Rubygems: https://rubygems.org/gems/git_curate
`git_curate` is a very simple tool that extends `git` with a `curate` subcommand. This lets you step through your local branches ergonomically, showing basic information about each, and letting you either keep or delete each one as you go. Alternatively, you can run it non-interactively and simply see a readable summary of your local branches.
* You could do something like this with a GUI tool. `git_curate` is for people who don't want to leave the `git` CLI.
* You could write a script to automatically delete every branch satisfying some set of criteria or other. `git_curate` is for people who for various reasons …
> Add git_curate

- README.md
fast_underscore
* [github](https://github.com/kddeisz/fast_underscore)
* [rubygems](https://rubygems.org/gems/fast_underscore)
A C-extension for the `String#underscore` method from Rails.
I don't believe that are other similar ones besides `fast_blank`. This is `fast_blank` but for underscore.
> Add fast_underscore

- README.md
Text-based logic question captcha's for Rails 🚫🤖
ActsAsTextcaptcha provides spam protection for Rails models with text-based logic question captchas. Questions are fetched from [Rob Tuley's](https://twitter.com/robtuley) [textcaptcha.com](http://textcaptcha.com/). They can be solved easily by humans but are tough for robots to crack.
The gem can also be configured with your own questions; as an alternative, or as a fallback to handle any API issues. For reasons on why logic based captchas are a good idea visit [textcaptcha.com](http://textcaptcha.com).
There are no other logic question based captchas on the list, this is a fresh take on captchas that often goes unnoticed. 
---
* [GitHub](http://github.com/matthutchinson/acts_as_textcaptcha)
* …
> Add ActsAsTextcaptcha gem to Captchas section

- README.md
**Arli — Arduino Library Manager, searcher and installer.**
**Arli** is an Arduino library manager with the ability to search libraries, install a single library, or bundle any number of libraries with the project. Arli also is a new project generator based on the [`arduino-cmake`](https://github.com/arduino-cmake/arduino-cmake) build system.
Arli is a rather simple and easy to use command-line tool which offers several indispensable features that help with Arduino project development, in particular for much larger projects with many dependencies and external libraries.
What's more, is that projects generated by Arli's generate command are highly portable from one system to another. Anyone can download your project build/upload with very little work. …
> Add arli gem (a CLI-based Arduino Library Manager and new project generator)

- README.md
`credit_card_validations` repo moved to `didww` Organization.
> credit_card_validations repo moved to didww org

- README.md
Holidays
https://github.com/holidays/holidays
https://rubygems.org/gems/holidays
Functionality to deal with holidays in Ruby.
Extends Ruby's built-in Date and Time classes and supports custom holiday definition lists.
I didn't find any similar project in the list, and this one is very useful IMO.
---
> add holidays

- README.md
CableReady completes the ActionCable story and expands the utility of web sockets in your Rails app.
* [GitHub](https://github.com/hopsoft/cable_ready)
* [Docs](https://cableready.stimulusreflex.com)
* [Build a real-time Twitter clone in 10 mins with Rails, StimulusReflex and CableReady](https://dev.to/codefund/build-a-real-time-twitter-clone-10-mins-with-rails-and-stimulusreflex-5h5c)
CableReady helps you create great real-time user experiences by making it simple to trigger client-side DOM changes from server-side Ruby. It establishes a standard for interacting with the client via ActionCable web sockets. No need for custom JavaScript.
Possible interactions range from updating a single element's value to replacing entire sections of content. You can even dispatch client-side DOM events …
> Add cable_ready gem

- README.md
ComfyBootstrapForm https://github.com/comfy/comfy-bootstrap-form
It's a form builder that extends default `ActionView::Helpers::FormBuilder` in order to generate Bootstrap 4 markup for form elements.
Currently, this is the only form builder that properly supports Bootstrap 4 markup and works in Rails 5.2 by wrapping`form_with` form helper. Rails 5.0+ versions are also supported as `form_for` is wrapped as well. Other form builders are either very out-of-date or not planning to support Bootstrap 4 at all.
Now it's a direct dependency of [ComfortableMexicanSofa CMS](https://github.com/comfy/comfortable-mexican-sofa) that uses Bootstrap 4 in the admin area.
Cheers!
> Add ComfyBootstrapForm (Form Builder)

- README.md
https://github.com/github/view_component
https://www.ruby-toolbox.com/projects/view_component
https://rubygems.org/gems/view_component
Note: this project was recently renamed. The original name was `actionview-component`: https://www.ruby-toolbox.com/projects/actionview-component.
ViewComponent is a framework for building view components in Rails.
ViewComponents are Ruby classes that are used to render views. They take data as input and return output-safe HTML. Think of them as an evolution of the presenter/decorator/view model pattern, inspired by React Components.
ViewComponent is similar to other view component libraries, but is specifically designed for tight conceptual integration into Rails. It is an extraction from the GitHub monolith.
It is compatible with the support for …
> add view_component

- README.md
[que-scheduler](https://github.com/hlascelles/que-scheduler) is a lightweight cron scheduler for the async job worker [que](https://github.com/chanks/que).
* Github: https://github.com/hlascelles/que-scheduler
* Rubygems: https://rubygems.org/gems/que-scheduler
* Downloads: 22k+ 
* Actively maintained
que-scheduler is an extension to [que](https://github.com/chanks/que) that adds support for scheduling items using a cron style configuration file.
It is similar to resque-scheduler (in terms of config syntax) but is for use with projects that are based on the que framework, with its greater reliability and ACID scheduling guarantees.
> Add que-scheduler

- README.md
Git Lint is the official port of the original Git Cop project that
avoids references to violence or violent terminology that might make
anyone feel unwelcome. The name change was necessary in order to better
support the [Black Lives Matter](https://blacklivesmatter.com) and
[Defund Police](https://8cantwait.org) movements.
This is a replacement/update to the original Git Cop link.
No difference in features between Git Cop and Git Lint. Git Lint is a direct port but with a better name.
---
> Updated to Git Lint 1.0.0

- README.md
- [Github](https://github.com/procore/blueprinter)
- [RubyGems](https://rubygems.org/gems/blueprinter/versions/0.6.0)
Blueprinter is a JSON Object Presenter for Ruby that takes business objects and breaks them down into simple hashes and serializes them to JSON. It can be used in Rails in place of other serializers (like JBuilder or ActiveModelSerializers). It is designed to be simple, direct, and performant.
It heavily relies on the idea of views which, similar to Rails views, are ways of predefining output for data in different contexts.
---
> Add blueprinter as API builder library

- README.md
ImageProcessing
https://github.com/janko/image_processing
https://rubygems.org/gems/image_processing
ImageProcessing provides higher-level image processing helpers that are commonly needed when handling image uploads. This gem can process images with either ImageMagick/GraphicsMagick or libvips libraries.
ImageProcessing's goal is to have a single gem that contains all the helper methods needed to resize and process images. Currently, existing attachment gems (like Paperclip, CarrierWave, Refile, Dragonfly, ActiveStorage, and others) implement their own custom image helper methods. But this isn't very DRY.
---
> Add image_processing gem

- README.md
- https://rubygems.org/gems/acts_as_api/versions/0.4.2
- https://github.com/fabrik42/acts_as_api
Describe features.
- DRY templates for your api responses
- Ships with support for ActiveRecord and Mongoid
- Plays very well together with client libs like Backbone.js, RestKit (iOS) or gson (Android).
- Easy but very flexible syntax for defining the templates
- XML, JSON and JSON-P support out of the box, easy to extend
- Minimal dependecies (you can also use it without Rails)
- Supports multiple api rendering templates per model. This is especially useful for API versioning or for example for private vs. public access points to a user’s profile.
- Easy to use :heart: 
- Supports multiple api rendering templates per model .
- Easy Integrations with templates .
- Ease of creating and …
> Add acts_as_api gem

- README.md
Name: tapping_device
Url: https://github.com/st0012/tapping_device
Blog Posts:
- [Debug Rails issues effectively with tapping_device](https://dev.to/st0012/debug-rails-issues-effectively-with-tappingdevice-c7c)
- [Want to know more about your Rails app? Tap on your objects!](https://dev.to/st0012/want-to-know-more-about-your-rails-app-tap-on-your-objects-bd3)
[tapping_device](https://github.com/st0012/tapping_device) is a tool that allows users to track certain events happen on a specific object (like method calls). This means a user can observe its program from a certain object's perspective. It's helpful for debugging purposes or understand an unfamiliar codebase.
AFAIK, there's no similar project at the moment.
> Add tapping_device

- README.md
[![Truemail](https://truemail-rb.org/assets/images/truemail_logo.png)](https://truemail-rb.org)
Configurable framework agnostic plain Ruby 📨 email validator. Helps to validate/verify emails via Regex, DNS and SMTP.
**Project page:** https://truemail-rb.org/truemail-gem
**GitHub:** https://github.com/rubygarage/truemail
**RubyGems:** https://rubygems.org/gems/truemail
1. Configurable layer-designed validator
2. Minimal runtime dependencies
3. Supporting of internationalized emails (EAI)
4. Whitelist/blacklist validation's layers
5. Simple SMTP debugger
6. Event logger
7. Host auditor tools (helps to detect common host problems interfering to proper email verification)
8. JSON serializers for audition and validation results
It's OOAK email vaildator in a Ruby World.
---
Please help us to …
> Add Truemail gem to Email section

- README.md
Hey @markets 
just fixing a link to GitHub as the thredded site is down.
Cheers!
> Changing thredded to GH link - site is down.

- README.md
As requested by @markets in #1016
https://railsnew.io
Closes #1016 
The simplest way to generate a new Rails app with (or without!) all the bells and whistles.
See #1016 
---
> Add railsnew.io

- README.md
Website: https://www.bridgetownrb.com
Repo: https://github.com/bridgetownrb/bridgetown
Docs: https://www.bridgetownrb.com/docs/
> Bridgetown is a Webpack-aware, Ruby-powered static site generator for the modern Jamstack era. Bridgetown takes your content, API data, and frontend assets; renders templates in Markdown, Liquid, ERB, and many other formats; and exports a complete website ready to be served by fast Jamstack services like Netlify or traditional web servers like Nginx.
See https://www.bridgetownrb.com/about/
> Bridgetown started life as a fork of the granddaddy of static site generators, Jekyll.
> But as the concepts of modern static site generation and the Jamstack came to the forefront, a whole new generation of tools rose up, like Hugo, Eleventy, Gatsby, and many more. In the …
> Add Bridgetown

- README.md
[Simple Scheduler](https://github.com/simplymadeapps/simple_scheduler), an enhancement for Heroku Scheduler + Sidekiq for scheduling jobs at specific times. [Check out our intro blog post to learn more](http://www.simplymadeapps.com/blog/2017/01/simple-scheduler-schedule-recurring-tasks-to-run-at-any-interval/).
Simple Scheduler is a scheduling add-on that is designed to be used with [Sidekiq](http://sidekiq.org) and [Heroku Scheduler](https://elements.heroku.com/addons/scheduler). It gives you the ability to **schedule tasks at any interval** without adding a clock process. Heroku Scheduler only allows you to schedule tasks every 10 minutes, every hour, or every day.
Every option we evaluated seems to have the same flaw: **If your server is down, your job won't run.** With Simple …
> Simple Scheduler

- README.md
`cql` gem added to 'Testing, Extras' category.
CQL
GitHub: https://github.com/enkessler/cql
RubyGems: https://rubygems.org/gems/cql
RubyToolbox: https://www.ruby-toolbox.com/projects/cql
CQL is a domain specific language used for querying a Cucumber (or other Gherkin based) test suite. It is built on top of the `cuke_modeler` gem and the goal of CQL is to increase the ease with which useful information can be extracted from a modeled test suite and turned into summarized data or reports.
As far as I know, there are no similar projects.
---
> Add cql gem

- README.md
💎 Ruby DNS mock. Mimic any DNS records for your test environment and even more.
**GitHub:** https://github.com/mocktools/ruby-dns-mock
**RubyGems:** https://rubygems.org/gems/dns_mock
1. Ability to mimic any DNS records (`A`, `AAAA`, `CNAME`, `MX`, `NS`, `PTR`, `SOA` and `TXT`)
2. Zero runtime dependencies
3. Lightweight UDP DNS mock server with dynamic/manual port assignment
4. Test framework agnostic (it's PORO, so you can use it outside of `RSpec`, `Test::Unit` or `MiniTest`)
5. Simple and intuitive DSL
6. `RSpec` out of the box support
The first flexible DNS mocking tool for Ruby 💎
---
> Technical/Add DnsMock to Testing section, Mock subsection

- README.md
Ciri - Ruby implementation of Ethereum
Ciri - https://github.com/ciri-ethereum/ciri
Ethereum implementation.
There is already a ruby implementation of Ethereum project, but seems it is deprecated(this https://github.com/cryptape/ruby-ethereum).
So I think Ciri is the only actively development Ruby implementation of Ethereum.
---
> Add Ciri - Ruby implementation of Ethereum

- README.md
Title:  <code>markdown_helper</code>
GitHub:  https://github.com/BurdetteLamar/markdown_helper#markdown-helper
RubyGems:  https://rubygems.org/gems/markdown_helper
<code>markdown_helper</code> is a markdown pre-processor implementing:
* File inclusion (which GitHub has so far refused to support), including nested includes, code highlighting, pre-formatted text.
* Page TOC (table of contents).
> Adding markdown_helper

- README.md
`cuke_modeler` gem added to 'Testing, Extras' category.
CukeModeler
GitHub: https://github.com/enkessler/cuke_modeler
RubyGems: https://rubygems.org/gems/cuke_modeler
RubyToolbox: https://www.ruby-toolbox.com/projects/cuke_modeler
CukeModeler models test suites written in Gherkin (i.e. `.feature` files) so that they can then be analyzed/manipulated programatically. It is essentially an abstraction layer that sits on top of the `gherkin`/`cucumber-gherkin` gem and is easier and more stable to work with than using those gems directly.
The only similar project is the `gherkin` gem itself, which `cuke_modeler` abstracts away. So...there aren't really any similar projects.
---
> Add cuke_modeler gem

- README.md
**cache_crispies**
https://github.com/codenoble/cache-crispies
https://rubygems.org/gems/cache_crispies
https://codenoble.com/blog/introducing-cache-crispies/
A Rails JSON serialization gem that focuses on performance with fast render times, bulit-in caching and a simple, readable DSL.
This project is focused on performance both in it's basic render times and in the fact that it has built-in caching. Also, it doesn't force any particular JSON standard like JSON:API, as many other popular serializers do.
---
> Add cache_crispies gem

- README.md
Name: `attr-gather`
GitHub: https://github.com/ianks/attr-gather
RubyGems: https://rubygems.org/gems/attr-gather
[attr-gather](https://github.com/ianks/attr-gather) - A gem for creating workflows that "enhance" entities with extra attributes. At a high level, [attr-gather](https://github.com/ianks/attr-gather) provides a process to fetch information from many data sources (such as third party APIs, legacy databases, etc.) in a fully parallelized fashion.
- Offers DSL for defining workflows and merging the results from each task
- Execution engine optimally parallelizes the execution of the workflow dependency graph
- Easily testable
- Ability to filter out bad data using schemas with [dry-validation](https://dry-rb.org/gems/dry-validation)
- Operates on a single entity rather than a list, …
> Add attr-gather gem to list

- README.md
arel_extensions - https://github.com/faveod/arel-extensions
Extending Arel: more "rubyish" syntax, functions for strings, dates, math... and add native extensions for some DBs.
```
uat = User.arel_table
User.where(uat[:login] =~ /test/)
User.select((uat[:first_name] + ' ' + uat[:last_name]).as('full_name')).limit(10).map(&:full_name)
((uat[:birthdate] - Date.today) * -1).to_sql
```
I didn't see similar projects, which is why we did it.
---
> Added arel_extensions

- README.md
* GitHub: https://github.com/cyril/accept_language.rb
* Gem: https://rubygems.org/gems/accept_language
A tiny library for parsing the `Accept-Language` header from browsers (as defined in [RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616#section-14.4)).
```ruby
AcceptLanguage.parse("da, en;q=0.8, ug;q=0.9").match("en-GB", "ug-CN")  # => "ug-CN"
```
This tool is:
* thread-safe
* well-maintained
* really minimalist
* handle super tricky use-cases
* case, type and language-agnostic
* Rails, Rack & I18n independent
* BCP-47 support
* MIT licensed
---
> Add `accept_language`

- README.md
[Vite Ruby]: https://github.com/elmassimo/vite_ruby
[website]: https://vite-ruby.netlify.app/
[vite.js]: https://vitejs.dev/
- [Repo][Vite Ruby]
- [Website]
An umbrella project with libraries that allow to easily integrate [Vite.js] in your favourite Ruby framework, such as Rails, Hanami, Padrino, and even [Jekyll sites](https://jekyll-vite.netlify.app/).
For example, `vite-rails` provides a complete setup for Rails applications, making it a suitable alternative to sprockets or webpacker.
Vite Ruby enables using Vite.js which—unlike Webpack—does not bundle code during development, which means the dev server is extremely fast to start, and changes are updated instantly.
In production, Vite.js bundles your code using Rollup.js which provides tree-shaking, lazy-loading, and common chunk …
> Add Vite Ruby

- README.md
Fixed URL typo for Rails Open Source App Gallery
The original was linked to some third-party organization.
> Fixing url typo for Rails Open Source App Gallery

- README.md
The current description was particularly inaccurate, and makes it look like httpx is an extension to httprb, which is not (it's its own gem).
> Updating httpx description

- README.md
* https://gitlab.com/honeyryderchuck/rodauth-oauth
* https://honeyryderchuck.gitlab.io/rodauth-oauth
* https://honeyryderchuck.gitlab.io/httpx/2021/03/15/oidc-provider-on-rails-using-rodauth-oauth.html
rodauth-oauth is a plugin for rodauth for building OAuth and OpenID providers.
* being built on top of rodauth, it's ideal for non-rails apps (but can be used in rails via `rodauth-rails`)
* lower footprint, easy setup, faster bootstrap (read the linked blog post), focus on security
* lots of advanced features (read the [wiki](https://honeyryderchuck.gitlab.io/rodauth-oauth/wiki/Home.html))
* ships both Oauth 2.0 and OpenID, making sure both layers work together
* supports SAML assertion tokens and MAC auth scheme
* [why you should use rodauth-oauth instead of …
> Adding rodauth-oauth

- README.md
- [Standard](https://github.com/testdouble/standard)
Standard is a code formatter based on Rubocop, and it comes with its own predfined styleguide, linter, and fixer. It's great for those who want an opinionated formatter and don't really want to define their own rules.
Enumerate comparisons.
- No configuration.
- Automatically format code.
- Catch style issues & programmer errors early
---
> Add Standard Code Formatter

- README.md
**API Guard**
* https://github.com/Gokul595/api_guard
* https://rubygems.org/gems/api_guard
JSON Web Token (JWT) based authentication solution with token refreshing & blacklisting for APIs built on Rails. This is built using [Ruby JWT](https://github.com/jwt/ruby-jwt) gem.
**Below are some of the similar gems and the main differences:**
* [knock](https://github.com/nsarno/knock) 
- This is supported only in Rails API-only application but, API Guard works in normal Rails app too.
- This doesn't have token refreshing and blacklisting but, API Guard has.
* [Devise::JWT](https://github.com/waiting-for-dev/devise-jwt)
- This works only with combination of devise gem but, API Guard works without devise.
Moreover, this gem was built with inspiration of devise gem to make the whole setup of API …
> Added API Guard gem

- README.md
Hey 👋 Thanks for this awesome list 👍 
I found that the [railsnew.io](https://github.com/markets/awesome-ruby/compare/railsnew.io) has not been maintained [since a year ago](https://github.com/miatrinity/rails_new_io).
And if you click on the url it will take you to a spam website. 😞 I think we'd better remove it.
Cheers.
> Remove unmaintained website railsnew.io

- README.md
Whatsapp SDK:
Github: https://github.com/ignacio-chiazzo/ruby_whatsapp_sdk
RubyGem: https://rubygems.org/gems/whatsapp_sdk
Project Page: https://ignacio-chiazzo.github.io/ruby_whatsapp_sdk
Use the Ruby Whatsapp SDK to communicate with Whatsapp API using the Cloud API. Create bots to send and receive messages using the Whatsapp SDK in a few minutes.
Enumerate comparisons.
- I didn't find any library that have all the features I needed so I created one. 
List of features:
- Medias API - Manage Medias.
- Messages API - Manage any type of message (text, audio, document, button etc). It also allows sending links etc.
- The gem can use either JSON or objects to talk to the API. This is useful when working with multiple integrations.
- Phone Numbers API - Manage Phone Numbers.
> Add whatsapp ruby gem

- README.md
💎 Ruby SMTP mock. Mimic any SMTP server behaviour for your test environment with fake SMTP server. 
**GitHub:** https://github.com/mocktools/ruby-smtp-mock
**RubyGems:** https://rubygems.org/gems/smtp_mock
**RubyWeekly:** https://rubyweekly.com/issues/623
1. Ability to handle configurable behaviour and life cycles of SMTP mock server(s)
2. Dynamic/manual port assignment
3. Test framework agnostic (it's PORO, so you can use it outside of `RSpec`, `Test::Unit` or `MiniTest`)
4. Simple and intuitive DSL
5. RSpec integration out of the box
6. Includes easy system dependency manager
The first flexible SMTP mocking tool for Ruby 💎
---
> Technical/Add SmtpMock to Testing section, Mock subsection

- README.md
I was shocked to see this wasn't already on this list.
- Simple Rails & AWS Lambda Integration using Rack
- It's a great DX since it's "just a Rails app" in a single lambda.
- It brings a lot of traditional thinking into a "serverless" realm
- There are other gems in the lamby ecosystem like [Lambdakiq](https://github.com/customink/lambdakiq) for a sidekiq-like approach to using SQS
---
> Add Lamby to serverless section

- README.md
**MemoWise** is the wise choice for Ruby memoization.
Title and urls (GitHub, RubyGems, project page, blog posts, ...).
* [Github](https://github.com/panorama-ed/memo_wise)
* [RubyGems](https://rubygems.org/gems/memo_wise)
* RubyConf 2021: Achieving Fast Method Meta-programming: Lessons from MemoWise ([slides](https://docs.google.com/presentation/d/1XgERQ0YHplwJKM3wNQwZn584d_9szYZp2WsDEXoY_7Y/edit?usp=sharing) / [benchmarks](https://gist.github.com/JacobEvelyn/17b7b000e50151c30eaea928f1fcdc11))
* Blog posts:
* [Introducing: MemoWise](https://medium.com/building-panorama-education/introducing-memowise-51a5f0523489)
* [Optimizing MemoWise Performance](https://ja.cob.land/optimizing-memowise-performance)
* [Esoteric Ruby in MemoWise](https://jemma.dev/blog/esoteric-ruby-in-memowise)
Describe …
> Add MemoWise

- README.md
Piggybak repository is now archived:
>This repository has been archived by the owner on Jul 16, 2020. It is now read-only.
Blog post about sunsetting the gem:
https://www.endpointdev.com/blog/2018/02/sunsetting-piggybak/
> Remove archived repository Piggybak

- README.md
* GitHub: https://github.com/fatkodima/online_migrations
* RubyGems: https://rubygems.org/gems/online_migrations
An established gem to run PostgreSQL migrations safely and easily. It has code helpers for table/column renaming, changing column type, adding columns with default, background migrations, etc. Additionally it a has a powerful framework to run large data changes via background migrations.
It is an alternative to [`strong_migrations`](https://github.com/ankane/strong_migrations). There is a [comparison](https://github.com/fatkodima/online_migrations#comparison-to-strong_migrations) in the project's readme.
---
> Add `online_migrations` gem

- README.md
- https://github.com/getsentry/sentry-ruby
- https://rubygems.org/gems/sentry-ruby/
It's the new Sentry SDK for Ruby, which replaces the old Raven Ruby library.
- According to the latest [Ruby and Rails Community Survey](https://rails-hosting.com/2022/#which-error-tracking-tools-do-you-use-in-production), Sentry is the most popular option for error monitoring. So I think it's worth being included in the section.
- The old Raven Ruby has been deprecated for 3 years, and the new `sentry-ruby` gem now has been downloaded for more than 27 million times ([link](https://rubygems.org/gems/sentry-ruby/)).
---
> Replace Raven Ruby with Sentry Ruby

- README.md
JobIteration from Shopify
* https://github.com/Shopify/job-iteration
* https://rubygems.org/gems/job-iteration
SidekiqIteration
* https://github.com/fatkodima/sidekiq-iteration
* https://rubygems.org/gems/sidekiq-iteration
JobIteration - an ActiveJob extension to make long-running jobs interruptible and resumable.
SidekiqIteration - is a JobIteration, but adapted to work with raw Sidekiq.
There are no alternatives to these gems.
> Add `job-iteration` and `sidekiq-iteration`

- README.md
Shakapacker
- [GitHub](https://github.com/shakacode/shakapacker)
- [RubyGems](https://rubygems.org/gems/shakapacker)
Use webpack to manage app-like JavaScript modules in Rails.
Webpacker is retired, and Shakapacker is its official and actively maintained successor.
---
> Add Shakapacker, update Webpacker

- README.md
Source: https://github.com/jjb/ruby-clock
RubyGems: https://rubygems.org/gems/ruby-clock
a scheduler which can replace cron. runs jobs in a persistent process, each in their own thread
1. based on venerable rufus for scheduling mechanics
2. runs jobs in persistent process
3. easy to configure to be a good citizen running in environments like heroku
> Add ruby-clock

- README.md
Nokolexbor
Github: https://github.com/serpapi/nokolexbor
Rubygem: https://rubygems.org/gems/nokolexbor (13k+ downloads for now, 3 months old)
High-performance HTML5 parser based on [Lexbor](https://github.com/lexbor/lexbor) (C engine), with support for both CSS selectors and XPath.
- Meant to be a drop-in replacement for [Nokogiri](https://nokogiri.org/).
- [5.2x faster at parsing HTML and up to 997x faster at CSS selectors than Nokogiri](https://github.com/serpapi/nokolexbor#benchmarks).
> [html-xml-parsing] Add Nokolexbor

- README.md
- https://github.com/tompng/katakata_irb
- https://rubygems.org/gems/katakata_irb
KatakataIrb might provide a better autocompletion based on type analysis to irb (an irb plugin).
This gem was [introduced in RubyKaigi 2023](https://rubykaigi.org/2023/presentations/tompng.html).
As far as I know, there are no similar projects.
---
> Add KatakataIrb gem

- README.md
ruby-spellchecker [https://github.com/omohokcoj/ruby-spellchecker](https://github.com/omohokcoj/ruby-spellchecker)
RubyGems: https://rubygems.org/gems/ruby-spellchecker
It helps to eliminate common spelling and grammar errors from the text (to prepare it for NLP for instance).
Other ruby spellchecking gems are quite outdated and not maintained. Many of them use hunspell-ffi to check all words from the text against existing English dictionaries and to suggest corrections based on jaro/levenshtein distance. Hunspell's approach can produce many false positives and requires shared libraries to be installed. This gem uses a large list of common errors collected from various open sources so it doesn't produce false positives and can be used for autocorrection. Also, it's written in pure ruby.
> Add ruby-spellchecker

- README.md
https://github.com/fatkodima/fast_count
https://rubygems.org/gems/fast_count
Allows to quickly get an estimated number of records in large tables. While `select count(*)` can take minutes or tens of minutes for large tables, this gem allows to get a 99% accuracy estimate for PostgreSQL within milliseconds.
Was featured twice on Ruby Weekly: [one](https://rubyweekly.com/issues/651) and [two](https://rubyweekly.com/issues/664).
**Note**: I added this gem under `Optimizations` section. But it also suits to `ORM/ODM Extensions`.
> Add `fast_count`

- README.md
https://github.com/westonganger/active_snapshot
https://rubygems.org/gems/active_snapshot
From the Readme
> Simplified snapshots and restoration for ActiveRecord models and associations with a transparent white-box implementation.
> 
> Key Features:
> 
>     Create and Restore snapshots of a parent record and any specified child records
>     Predictible and explicit behaviour provides much needed clarity to your restore logic
>     Snapshots are created upon request only, we do not use any callbacks
>     Tiny method footprint so its easy to completely override the logic later
> 
> Why This Library:
> 
> Model Versioning and Restoration require concious thought, design, and understanding. You should understand your versioning and restoration process completely. This gem's small API and …
> Add active_snapshot

- README.md
Hi,
I'm the maintainer of Retest, a file system listener gem that supports most testing conventions by default.
I'd like to reference the project on the awesome-ruby repo.
Retest has over 95,000 downloads on Rubygems and 120 stars on GitHub. 
I've personally been using and maintaining Retest daily for the last 4 years.
* https://github.com/alexb52/retest
* https://rubygems.org/gems/retest
Retest is a small command-line tool that helps you refactor code by watching a file change and running its matching spec. Designed to be dev-centric and project-independent, it can be used on the fly. No Gemfile updates, no commits to a repo, and no configuration files are required to start refactoring. Works with every Ruby project (at least that is the end goal)
Like `Guard`, Retest is a file system …
> Add retest gem under File System Listener section

- README.md
Multiwoven - https://github.com/Multiwoven/multiwoven
Open-source reverse ETL, data activation platform for data teams developed on Ruby on Rails
I haven't seen any other reverse ETL platform built on Ruby on Rails
> Add Multiwoven

- README.md
fitting
https://github.com/tuwilof/fitting
https://rubygems.org/gems/fitting
Library add improve test log for RSpec and WebMock, validate its according to API Blueprint and Open API, show the documentation coverage with log.
Test log setting supports RSpec test and WebMock stubbing for Ruby On Rails application, API documentation supports API Blueprint and OpenAPI.
This reduces the costs of support, testers and analysts.
---
> Add `fitting`

- README.md
positioning: https://github.com/brendon/positioning
Simple positioning for ActiveRecord models. Supports more than one list per model and relative positioning.
A combination of ActsAsList and Ranked-Model. Architecturally more like Ranked-Model (keeps the model namespace clean) but uses non-sparse integers for ranking position (like ActsAsList) with better controls to ensure list integrity.
Closes #1141
> Add positioning to Sorting list

- README.md
Adds `AnnotateRb` gem to the list of gems.
[Rubygems](https://rubygems.org/gems/annotaterb)
[Github repo](https://github.com/drwl/annotaterb)
It's an active and maintained hard fork of the old Annotate gem. It improves the developer experience by adding model database schemas as text comments in corresponding ActiveRecord models. It also supports annotating routes.
It's actively maintained compared to it's predecessor, the Annotate gem.
> Add `AnnotateRb` gem

- README.md
The https://sider.review link is broken (404). Turns out Sider shut down in 2022.
Here's a tweet confirming it: https://x.com/sumyapp/status/1609398943594733568
related: https://github.com/markets/awesome-ruby/pull/494
> Remove Sider

- README.md
https://github.com/ZhgChgLi/ZMediumToMarkdown
A powerful tool that allows you to effortlessly download and convert your Medium posts to Markdown format.
ZMediumToMarkdown: Focuses on downloading and converting Medium posts to Markdown, ideal for users looking to archive or migrate their content.
---
> Add ZMediumToMarkdown

- README.md
[PacketFu](https://github.com/packetfu/packetfu) is packet analysis library. It enables sniffing and injecting packets to an interface.
This project is a decade old packet analysis library. It allows packet manipulation and dissection through high level  abstraction.
This project is similar to the popular `Scapy` library for Python. I'm not sure whether a similar project exists for Ruby. 
This PR resolves #1157.
> Add PacketFu

- README.md
AnywayConfig - Configuration library for Ruby gems and applications
- https://github.com/palkan/anyway_config
- https://rubygems.org/gems/anyway_config
- https://evilmartians.com/opensource/anyway-config
- https://www.rubydoc.info/gems/anyway_config/1.4.1
[Anyway Config](https://github.com/palkan/anyway_config) is a gem that allows you to manage different sources of data transparently. Moreover, it makes your code independent of the way you store your settings by introducing configuration classes. No more Rails.credentials, Rails.application.config_for, or ENV calls; you only need to deal with Ruby classes.
---
> Add AnywayConfig
